In [ ]:
import pandas as pd

df = pd.read_csv("/content/Nassau Candy Distributor.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
# Check number of rows and columns
print("Rows and Columns:", df.shape)

# Display all column names
print("\nColumn Names:")
print(df.columns.tolist())

Rows and Columns: (5404, 18)

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost']

In [ ]:
# Check missing values in each column
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      1
Sales             1
Units             1
Gross Profit      1
Cost              1
dtype: int64

In [ ]:
# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5404 entries, 0 to 5403
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          5404 non-null   int64
 1   Order ID        5404 non-null   object
 2   Order Date      5404 non-null   object
 3   Ship Date       5404 non-null   object
 4   Ship Mode       5404 non-null   object
 5   Customer ID     5404 non-null   int64
 6   Country/Region  5404 non-null   object
 7   City            5404 non-null   object
 8   State/Province  5404 non-null   object
 9   Postal Code     5404 non-null   object
 10  Division        5404 non-null   object
 11  Region          5404 non-null   object
 12  Product ID      5404 non-null   object
 13  Product Name    5403 non-null   object
 14  Sales           5403 non-null   float64
 15  Units           5403 non-null   float64
 16  Gross Profit    5403 non-null   float64
 17  Cost            5403 non-null   float64
dtypes: float64(4), int64(2), object(12)
memory usage: 760.1+ KB

In [ ]:
# Numerical columns summary
df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,5404.000000,5404.000000,5403.000000,5403.000000,5403.000000,5403.000000
mean,2702.500000,134460.500925,13.827165,3.791782,9.112049,4.715116
std,1560.144758,20208.530292,11.118475,2.221981,6.547889,4.951217
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,1351.750000,116825.250000,7.200000,2.000000,4.900000,2.400000
50%,2702.500000,133588.500000,10.800000,3.000000,7.470000,3.600000
75%,4053.250000,152136.750000,18.000000,5.000000,12.250000,5.700000
max,5404.000000,187423.000000,260.000000,14.000000,130.000000,130.000000

In [ ]:
# Check unique values in important categorical columns

print("Ship Modes:")
print(df["Ship Mode"].unique())

print("\nDivisions:")
print(df["Division"].unique())

print("\nRegions:")
print(df["Region"].unique())

Ship Modes:
['Standard Class' 'First Class' 'Second Class' 'Same Day']

Divisions:
['Chocolate' 'Other' 'Sugar']

Regions:
['Interior' 'Atlantic' 'Gulf' 'Pacific']

In [ ]:
# Number of unique products
print("Unique Products:", df["Product Name"].nunique())

# Top 10 products by order count
print(df["Product Name"].value_counts().head(10))

Unique Products: 15
Product Name
Wonka Bar - Milk Chocolate           1158
Wonka Bar -Scrumdiddlyumptious       1115
Wonka Bar - Triple Dazzle Caramel    1063
Wonka Bar - Fudge Mallows             966
Wonka Bar - Nutty Crunch Surprise     919
Wonka Gum                              65
Kazookles                              58
Lickable Wallpaper                     41
Laffy Taffy                             4
SweeTARTS                               4
Name: count, dtype: int64

In [ ]:
# Display important numerical columns
df[["Sales", "Units", "Gross Profit", "Cost"]].head(10)

   Sales  Units  Gross Profit  Cost
0   6.50    2.0          4.22  2.28
1   7.50    2.0          4.90  2.60
2  10.47    3.0          7.47  3.00
3  10.80    3.0          7.50  3.30
4  11.25    3.0          7.35  3.90
5  32.40    9.0         22.50  9.90
6   7.50    2.0          4.90  2.60
7   9.75    3.0          6.33  3.42
8   6.98    2.0          4.98  2.00
9  13.00    4.0          8.44  4.56

In [ ]:
# Display first few order and ship dates
print(df[["Order Date", "Ship Date"]].head(10))

   Order Date   Ship Date
0  03-01-2024  30-06-2026
1  04-01-2024  01-07-2026
2  04-01-2024  01-07-2026
3  04-01-2024  01-07-2026
4  05-01-2024  05-07-2026
5  06-01-2024  03-07-2026
6  06-01-2024  03-07-2026
7  06-01-2024  30-06-2026
8  06-01-2024  03-07-2026
9  06-01-2024  03-07-2026

In [ ]:
# Check unusual numerical values

print("Sales <= 0:", (df["Sales"] <= 0).sum())
print("Units <= 0:", (df["Units"] <= 0).sum())
print("Cost < 0:", (df["Cost"] < 0).sum())

Sales <= 0: 0
Units <= 0: 0
Cost < 0: 0

In [ ]:
# Verify Gross Profit = Sales - Cost
df["Calculated Profit"] = df["Sales"] - df["Cost"]

print(df[["Sales", "Cost", "Gross Profit", "Calculated Profit"]].head(10))

   Sales  Cost  Gross Profit  Calculated Profit
0   6.50  2.28          4.22               4.22
1   7.50  2.60          4.90               4.90
2  10.47  3.00          7.47               7.47
3  10.80  3.30          7.50               7.50
4  11.25  3.90          7.35               7.35
5  32.40  9.90         22.50              22.50
6   7.50  2.60          4.90               4.90
7   9.75  3.42          6.33               6.33
8   6.98  2.00          4.98               4.98
9  13.00  4.56          8.44               8.44

In [ ]:
# Total sales, profit, and units

print("Total Sales:", df["Sales"].sum())
print("Total Units:", df["Units"].sum())
print("Total Gross Profit:", df["Gross Profit"].sum())
print("Total Cost:", df["Cost"].sum())

Total Sales: 74708.17
Total Units: 20487.0
Total Gross Profit: 49232.399999999994
Total Cost: 25475.77

In [ ]:
# Convert Order Date and Ship Date into datetime format

df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d-%m-%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d-%m-%Y")

print(df[["Order Date", "Ship Date"]].dtypes)

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [ ]:
# Calculate shipping lead time in days

df["Lead_Time_Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

df[["Order Date", "Ship Date", "Lead_Time_Days"]].head()

  Order Date  Ship Date  Lead_Time_Days
0 2024-01-03 2026-06-30             909
1 2024-01-04 2026-07-01             909
2 2024-01-04 2026-07-01             909
3 2024-01-04 2026-07-01             909
4 2024-01-05 2026-07-05             912

In [ ]:
print("Average Lead Time:", df["Lead_Time_Days"].mean())
print("Minimum Lead Time:", df["Lead_Time_Days"].min())
print("Maximum Lead Time:", df["Lead_Time_Days"].max())

Average Lead Time: 1134.480754996299
Minimum Lead Time: 904
Maximum Lead Time: 1277

In [ ]:
# Calculate profit margin percentage

df["Profit_Margin"] = (
    df["Gross Profit"] / df["Sales"]
) * 100

df[["Sales", "Gross Profit", "Profit_Margin"]].head()

   Sales  Gross Profit  Profit_Margin
0   6.50          4.22      64.923077
1   7.50          4.90      65.333333
2  10.47          7.47      71.346705
3  10.80          7.50      69.444444
4  11.25          7.35      65.333333

In [ ]:
# Calculate profit earned per unit

df["Profit_Per_Unit"] = (
    df["Gross Profit"] / df["Units"]
)

df[["Units", "Gross Profit", "Profit_Per_Unit"]].head()

   Units  Gross Profit  Profit_Per_Unit
0    2.0          4.22             2.11
1    2.0          4.90             2.45
2    3.0          7.47             2.49
3    3.0          7.50             2.50
4    3.0          7.35             2.45

In [ ]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost', 'Calculated Profit', 'Lead_Time_Days', 'Profit_Margin', 'Profit_Per_Unit']

In [ ]:
factory_mapping = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

df["Factory"] = df["Product Name"].map(factory_mapping)

df[["Product Name", "Factory"]].head(20)

                         Product Name          Factory
0          Wonka Bar - Milk Chocolate  Wicked Choccy's
1   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
2   Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
3      Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
4   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
5      Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
6   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
7          Wonka Bar - Milk Chocolate  Wicked Choccy's
8   Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
9          Wonka Bar - Milk Chocolate  Wicked Choccy's
10         Wonka Bar - Milk Chocolate  Wicked Choccy's
11         Wonka Bar - Milk Chocolate  Wicked Choccy's
12     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
13          Wonka Bar - Fudge Mallows    Lot's O' Nuts
14         Wonka Bar - Milk Chocolate  Wicked Choccy's
15  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
16  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
17  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
18         Wonka Bar - Milk Chocolate  Wicked Choccy's
19                          Wonka Gum   Secret Factory

In [ ]:
print("Missing Factory Mapping:", df["Factory"].isna().sum())

Missing Factory Mapping: 1

In [ ]:
df.to_csv("Nassau_Candy_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
factory_analysis = df.groupby("Factory").agg(
    Orders=("Order ID", "nunique"),
    Sales=("Sales", "sum"),
    Gross_Profit=("Gross Profit", "sum"),
    Units=("Units", "sum"),
    Avg_Lead_Time=("Lead_Time_Days", "mean")
).reset_index()

factory_analysis

             Factory  Orders     Sales  Gross_Profit    Units  Avg_Lead_Time
0      Lot's O' Nuts    2513  40197.28      27780.18  11272.0    1135.026000
1     Secret Factory     105   4036.25       2036.45    441.0    1085.177570
2        Sugar Shack      15     88.64         48.89     42.0    1127.133333
3  The Other Factory      59    792.50         92.50    240.0    1126.516667
4    Wicked Choccy's    1824  29593.50      19274.38   8492.0    1136.320576

In [ ]:
region_analysis = df.groupby("Region").agg(
    Orders=("Order ID", "nunique"),
    Sales=("Sales", "sum"),
    Gross_Profit=("Gross Profit", "sum"),
    Avg_Lead_Time=("Lead_Time_Days", "mean")
).reset_index()

region_analysis.sort_values("Avg_Lead_Time", ascending=False)

     Region  Orders     Sales  Gross_Profit  Avg_Lead_Time
0  Atlantic    1335  22093.14      14483.08    1147.102769
1      Gulf     748  12728.54       8410.16    1133.067033
2  Interior    1020  16396.56      10898.83    1132.464847
3   Pacific    1414  23489.93      15440.33    1124.368072

In [ ]:
product_analysis = df.groupby("Product Name").agg(
    Orders=("Order ID", "nunique"),
    Units=("Units", "sum"),
    Sales=("Sales", "sum"),
    Gross_Profit=("Gross Profit", "sum"),
    Avg_Lead_Time=("Lead_Time_Days", "mean")
).reset_index()

product_analysis.sort_values("Gross_Profit", ascending=False).head(10)

,Product Name,Orders,Units,Sales,Gross_Profit,Avg_Lead_Time
13,Wonka Bar -Scrumdiddlyumptious,919,4149.0,14936.40,10372.50,1140.121076
12,Wonka Bar - Triple Dazzle Caramel,875,3989.0,14958.75,9773.05,1139.802446
10,Wonka Bar - Milk Chocolate,949,4503.0,14634.75,9501.33,1133.124352
9,Wonka Bar - Fudge Mallows,811,3651.0,13143.60,8762.40,1127.865424
11,Wonka Bar - Nutty Crunch Surprise,783,3472.0,12117.28,8645.28,1136.371055
6,Lickable Wallpaper,40,184.0,3680.00,1840.00,1076.853659
14,Wonka Gum,64,253.0,316.25,164.45,1087.538462
4,Kazookles,57,230.0,747.50,57.50,1121.448276
3,Hair Toffee,2,10.0,45.00,35.00,1273.500000
0,Everlasting Gobstopper,1,4.0,40.00,32.00,1273.000000

In [ ]:
# Create Lead Time column again

df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d-%m-%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d-%m-%Y")

df["Lead_Time_Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print("Lead Time column created successfully!")
print(df["Lead_Time_Days"].describe())

Lead Time column created successfully!
count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead_Time_Days, dtype: float64

In [ ]:
df.groupby("Ship Mode")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean", ascending=False)

                count         mean  median  min   max
Ship Mode
First Class      1548  1338.275840  1272.0  905  1638
Same Day          547  1333.442413  1269.0  904  1636
Second Class     1979  1323.845376  1273.0  906  1640
Standard Class   6120  1314.334641  1274.0  908  1642

In [ ]:
df.groupby("Region")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean", ascending=False)

          count         mean  median  min   max
Region
Interior   2335  1323.091221  1274.0  904  1642
Atlantic   2986  1322.745144  1274.0  904  1642
Pacific    3253  1322.194897  1274.0  904  1642
Gulf       1620  1311.374691  1274.0  904  1642

In [ ]:
df.groupby("Product Name")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean", ascending=False)

                                   count         mean  median   min   max
Product Name
Hair Toffee                            4  1455.250000  1455.0  1272  1639
Everlasting Gobstopper                 3  1394.666667  1273.0  1270  1641
SweeTARTS                             10  1383.500000  1274.0   910  1641
Laffy Taffy                           10  1383.100000  1275.0   909  1642
Lickable Wallpaper                    94  1339.138298  1274.0   904  1641
Wonka Bar - Nutty Crunch Surprise   1810  1328.915470  1274.0   904  1642
Wonka Bar - Triple Dazzle Caramel   2015  1325.661042  1274.0   904  1642
Wonka Bar -Scrumdiddlyumptious      2064  1320.641957  1274.0   904  1642
Wonka Bar - Milk Chocolate          2137  1316.764623  1274.0   904  1642
Wonka Bar - Fudge Mallows           1818  1314.242024  1274.0   904  1642
Wonka Gum                            120  1306.525000  1273.5   904  1642
Nerds                                  4  1274.000000  1274.0   908  1640
Fizzy Lifting Drinks                   6  1273.500000  1274.0   907  1640
Kazookles                             96  1272.989583  1273.0   904  1641
Fun Dip                                3  1272.666667  1272.0  1271  1275

In [ ]:
df.groupby("Country/Region")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean", ascending=False)

                count         mean  median  min   max
Country/Region
United States    9994  1321.461277  1274.0  904  1642
Canada            200  1289.890000  1273.5  904  1642

In [ ]:
df["Order Date"] = pd.to_datetime(df["Order Date"], errors='coerce')
df["Ship Date"] = pd.to_datetime(df["Ship Date"], errors='coerce')

df["Order_Year"] = df["Order Date"].dt.year
df["Ship_Year"] = df["Ship Date"].dt.year

df["Year_Gap"] = df["Ship_Year"] - df["Order_Year"]

df["Year_Gap"].value_counts().sort_index()

/tmp/ipykernel_4533/2297596062.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Ship Date"] = pd.to_datetime(df["Ship Date"], errors='coerce')

Year_Gap
2.0     301
3.0    1262
4.0     608
Name: count, dtype: int64

In [ ]:
year_gap_summary = (
    df["Year_Gap"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print(year_gap_summary)

Year_Gap
2.0    13.86
3.0    58.13
4.0    28.01
Name: proportion, dtype: float64

In [ ]:
# Recalculate Lead_Time_Days since the DataFrame was reloaded
df["Lead_Time_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

# Describe the column
df["Lead_Time_Days"].describe()

count    2171.000000
mean     1151.441271
std       210.487758
min       613.000000
25%       995.000000
50%      1180.000000
75%      1303.000000
max      1600.000000
Name: Lead_Time_Days, dtype: float64

In [ ]:
factory_mapping = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

df["Factory"] = df["Product Name"].map(factory_mapping)

df[["Product Name", "Factory"]].drop_duplicates().sort_values("Product Name")

                           Product Name            Factory
4729             Everlasting Gobstopper     Secret Factory
191                Fizzy Lifting Drinks        Sugar Shack
5007                            Fun Dip        Sugar Shack
4435                        Hair Toffee  The Other Factory
26                            Kazookles  The Other Factory
226                         Laffy Taffy        Sugar Shack
136                  Lickable Wallpaper     Secret Factory
1490                              Nerds        Sugar Shack
973                           SweeTARTS        Sugar Shack
13            Wonka Bar - Fudge Mallows      Lot's O' Nuts
0            Wonka Bar - Milk Chocolate    Wicked Choccy's
2     Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts
1     Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's
3        Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts
19                            Wonka Gum     Secret Factory
5403                                NaN                NaN

In [ ]:
df["Factory"].isna().sum()

np.int64(1)

In [ ]:
df[df["Factory"].isna()][["Product Name", "Product ID"]]

     Product Name Product ID
5403          NaN          C

In [ ]:
# Check Factory mapping coverage

print("Total rows:", len(df))
print("Mapped Factory rows:", df["Factory"].notna().sum())
print("Missing Factory rows:", df["Factory"].isna().sum())

Total rows: 5404
Mapped Factory rows: 5403
Missing Factory rows: 1

In [ ]:
df["Factory"].value_counts(dropna=False)

Factory
Lot's O' Nuts        3000
Wicked Choccy's      2221
Secret Factory        107
The Other Factory      60
Sugar Shack            15
NaN                     1
Name: count, dtype: int64

In [ ]:
df.groupby("Factory")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean", ascending=False)

                   count         mean  median     min     max
Factory
Sugar Shack            3  1269.000000  1116.0  1094.0  1597.0
The Other Factory     18  1153.555556  1213.0   785.0  1537.0
Lot's O' Nuts       1234  1152.694489  1178.0   617.0  1599.0
Wicked Choccy's      874  1151.243707  1183.0   613.0  1600.0
Secret Factory        42  1109.428571  1121.0   645.0  1539.0

In [ ]:
df.groupby(
    ["Factory", "Region"]
)["Lead_Time_Days"].agg(
    ["count", "mean", "median"]
).sort_values("mean", ascending=False)

                            count         mean  median
Factory           Region
Sugar Shack       Interior      2  1345.500000  1345.5
The Other Factory Atlantic      9  1250.111111  1333.0
Lot's O' Nuts     Atlantic    368  1190.605978  1213.0
Wicked Choccy's   Atlantic    285  1187.884211  1212.0
Secret Factory    Atlantic     12  1184.500000  1206.5
The Other Factory Interior      3  1160.333333  1154.0
Wicked Choccy's   Pacific     240  1142.345833  1142.0
Lot's O' Nuts     Interior    304  1138.292763  1155.0
                  Gulf        201  1138.164179  1155.0
                  Pacific     361  1134.265928  1125.0
Wicked Choccy's   Interior    201  1128.034826  1154.0
                  Gulf        148  1126.635135  1153.5
Secret Factory    Pacific      12  1121.333333  1129.0
Sugar Shack       Atlantic      1  1116.000000  1116.0
Secret Factory    Gulf          8  1085.250000  1184.5
The Other Factory Gulf          3  1038.333333   966.0
Secret Factory    Interior     10  1024.400000  1040.0
The Other Factory Pacific       3   972.333333   851.0
Sugar Shack       Gulf          0          NaN     NaN
                  Pacific       0          NaN     NaN

In [ ]:
factory_coordinates = {
    "Lot's O' Nuts": (32.881893, -111.768036),
    "Wicked Choccy's": (32.076176, -81.088371),
    "Sugar Shack": (48.119140, -96.181150),
    "Secret Factory": (41.446333, -90.565487),
    "The Other Factory": (35.117500, -89.971107)
}

df["Factory_Latitude"] = df["Factory"].map(
    lambda x: factory_coordinates.get(x, (None, None))[0]
)

df["Factory_Longitude"] = df["Factory"].map(
    lambda x: factory_coordinates.get(x, (None, None))[1]
)

df[[
    "Product Name",
    "Factory",
    "Factory_Latitude",
    "Factory_Longitude"
]].drop_duplicates()

,Product Name,Factory,Factory_Latitude,Factory_Longitude
0,Wonka Bar - Milk Chocolate,Wicked Choccy's,32.076176,-81.088371
1,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,32.076176,-81.088371
2,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,32.881893,-111.768036
3,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,32.881893,-111.768036
13,Wonka Bar - Fudge Mallows,Lot's O' Nuts,32.881893,-111.768036
19,Wonka Gum,Secret Factory,41.446333,-90.565487
26,Kazookles,The Other Factory,35.117500,-89.971107
136,Lickable Wallpaper,Secret Factory,41.446333,-90.565487
191,Fizzy Lifting Drinks,Sugar Shack,48.119140,-96.181150
226,Laffy Taffy,Sugar Shack,48.119140,-96.181150
973,SweeTARTS,Sugar Shack,48.119140,-96.181150
1490,Nerds,Sugar Shack,48.119140,-96.181150
4435,Hair Toffee,The Other Factory,35.117500,-89.971107
4729,Everlasting Gobstopper,Secret Factory,41.446333,-90.565487
5007,Fun Dip,Sugar Shack,48.119140,-96.181150
5403,NaN,NaN,NaN,NaN

In [ ]:
print("Unique Cities:", df["City"].nunique())
print("Unique States:", df["State/Province"].nunique())
print("Unique Postal Codes:", df["Postal Code"].nunique())

print("\nSample destination data:")
print(
    df[["Country/Region", "City", "State/Province", "Postal Code", "Region"]]
    .drop_duplicates()
    .head(20)
)

Unique Cities: 429
Unique States: 55
Unique Postal Codes: 525

Sample destination data:
   Country/Region            City  State/Province Postal Code    Region
0   United States         Houston           Texas       77095  Interior
1   United States      Naperville        Illinois       60540  Interior
4   United States    Philadelphia    Pennsylvania       19143  Atlantic
5   United States       Henderson        Kentucky       42420      Gulf
7   United States          Athens         Georgia       30605      Gulf
11  United States     Los Angeles      California       90049   Pacific
14  United States      Huntsville           Texas       77340  Interior
16  United States          Laredo           Texas       78041  Interior
18  United States     Springfield        Virginia       22153      Gulf
20  United States           Dover        Delaware       19901  Atlantic
21  United States   San Francisco      California       94109   Pacific
22  United States  Mount Pleasant  South Carolina       29464      Gulf
24  United States          Newark            Ohio       43055  Atlantic
25  United States    Bossier City       Louisiana       71111      Gulf
32  United States    Philadelphia    Pennsylvania       19140  Atlantic
33  United States         Roswell         Georgia       30076      Gulf
34  United States    Philadelphia    Pennsylvania       19134  Atlantic
38  United States     Springfield          Oregon       97477   Pacific
39  United States      Scottsdale         Arizona       85254   Pacific
43  United States       Jonesboro        Arkansas       72401      Gulf

In [ ]:
df["Region"].value_counts()

Region
Pacific     1660
Atlantic    1625
Interior    1209
Gulf         910
Name: count, dtype: int64

In [ ]:
df["Order_Year"] = df["Order Date"].dt.year
df["Ship_Year"] = df["Ship Date"].dt.year
df["Year_Gap"] = df["Ship_Year"] - df["Order_Year"]

print(df["Year_Gap"].value_counts().sort_index())

Year_Gap
2.0     301
3.0    1262
4.0     608
Name: count, dtype: int64

In [ ]:
df.groupby(["Order_Year", "Ship_Year"]).size().sort_values(ascending=False)

Order_Year  Ship_Year
2024.0      2027         830
            2028         537
2025.0      2028         432
2024.0      2026         301
2025.0      2029          71
dtype: int64

In [ ]:
print("Total rows:", len(df))
print("Mapped Factory rows:", df["Factory"].notna().sum())
print("Missing Factory rows:", df["Factory"].isna().sum())

print("\nMissing factory product:")
print(df.loc[df["Factory"].isna(), "Product Name"])

Total rows: 5404
Mapped Factory rows: 5403
Missing Factory rows: 1

Missing factory product:
5403    NaN
Name: Product Name, dtype: object

In [ ]:
print("Unique Products:", df["Product Name"].nunique())

print("\nProduct-wise order count:")
print(df["Product Name"].value_counts(dropna=False))

Unique Products: 15

Product-wise order count:
Product Name
Wonka Bar - Milk Chocolate           1158
Wonka Bar -Scrumdiddlyumptious       1115
Wonka Bar - Triple Dazzle Caramel    1063
Wonka Bar - Fudge Mallows             966
Wonka Bar - Nutty Crunch Surprise     919
Wonka Gum                              65
Kazookles                              58
Lickable Wallpaper                     41
Laffy Taffy                             4
SweeTARTS                               4
Fizzy Lifting Drinks                    3
Nerds                                   2
Hair Toffee                             2
Fun Dip                                 2
Everlasting Gobstopper                  1
NaN                                     1
Name: count, dtype: int64

In [ ]:
factory_region_counts = (
    df.groupby(["Factory", "Region"])
      .size()
      .reset_index(name="Order_Count")
      .sort_values("Order_Count", ascending=False)
)

print(factory_region_counts)

              Factory    Region  Order_Count
3       Lot's O' Nuts   Pacific          936
0       Lot's O' Nuts  Atlantic          883
16    Wicked Choccy's  Atlantic          681
2       Lot's O' Nuts  Interior          677
19    Wicked Choccy's   Pacific          673
1       Lot's O' Nuts      Gulf          504
18    Wicked Choccy's  Interior          495
17    Wicked Choccy's      Gulf          372
4      Secret Factory  Atlantic           34
7      Secret Factory   Pacific           32
6      Secret Factory  Interior           22
12  The Other Factory  Atlantic           22
5      Secret Factory      Gulf           19
15  The Other Factory   Pacific           17
13  The Other Factory      Gulf           12
14  The Other Factory  Interior            9
10        Sugar Shack  Interior            6
8         Sugar Shack  Atlantic            5
9         Sugar Shack      Gulf            3
11        Sugar Shack   Pacific            1

In [ ]:
factory_region_analysis = (
    df.groupby(["Factory", "Region"])["Lead_Time_Days"]
      .agg(["count", "mean", "median", "min", "max"])
      .reset_index()
      .sort_values("mean", ascending=False)
)

print(factory_region_analysis)

              Factory    Region  count         mean  median     min     max
10        Sugar Shack  Interior      2  1345.500000  1345.5  1094.0  1597.0
12  The Other Factory  Atlantic      9  1250.111111  1333.0   977.0  1537.0
0       Lot's O' Nuts  Atlantic    368  1190.605978  1213.0   670.0  1569.0
16    Wicked Choccy's  Atlantic    285  1187.884211  1212.0   613.0  1568.0
4      Secret Factory  Atlantic     12  1184.500000  1206.5   951.0  1539.0
14  The Other Factory  Interior      3  1160.333333  1154.0  1025.0  1302.0
19    Wicked Choccy's   Pacific    240  1142.345833  1142.0   673.0  1600.0
2       Lot's O' Nuts  Interior    304  1138.292763  1155.0   644.0  1597.0
1       Lot's O' Nuts      Gulf    201  1138.164179  1155.0   644.0  1599.0
3       Lot's O' Nuts   Pacific    361  1134.265928  1125.0   617.0  1598.0
18    Wicked Choccy's  Interior    201  1128.034826  1154.0   644.0  1597.0
17    Wicked Choccy's      Gulf    148  1126.635135  1153.5   644.0  1539.0
7      Secret Factory   Pacific     12  1121.333333  1129.0   730.0  1510.0
8         Sugar Shack  Atlantic      1  1116.000000  1116.0  1116.0  1116.0
5      Secret Factory      Gulf      8  1085.250000  1184.5   645.0  1365.0
13  The Other Factory      Gulf      3  1038.333333   966.0   785.0  1364.0
6      Secret Factory  Interior     10  1024.400000  1040.0   730.0  1269.0
15  The Other Factory   Pacific      3   972.333333   851.0   791.0  1275.0
9         Sugar Shack      Gulf      0          NaN     NaN     NaN     NaN
11        Sugar Shack   Pacific      0          NaN     NaN     NaN     NaN

In [ ]:
df["Order_Month"] = df["Order Date"].dt.month

print(df[["Order Date", "Order_Month"]].head())

  Order Date  Order_Month
0 2024-03-01          3.0
1 2024-04-01          4.0
2 2024-04-01          4.0
3 2024-04-01          4.0
4 2024-05-01          5.0

In [ ]:
df["Order_Year"] = df["Order Date"].dt.year

print(df[["Order Date", "Order_Year"]].head())

  Order Date  Order_Year
0 2024-03-01      2024.0
1 2024-04-01      2024.0
2 2024-04-01      2024.0
3 2024-04-01      2024.0
4 2024-05-01      2024.0

In [ ]:
ml_df = df.dropna(subset=["Product Name", "Factory"]).copy()

print("Original rows:", len(df))
print("ML dataset rows:", len(ml_df))
print("Removed rows:", len(df) - len(ml_df))

Original rows: 5404
ML dataset rows: 5403
Removed rows: 1

In [ ]:
from sklearn.preprocessing import OneHotEncoder

categorical_features = [
    "Product Name",
    "Factory",
    "Region",
    "Ship Mode"
]

encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

encoded_data = encoder.fit_transform(
    ml_df[categorical_features]
)

encoded_columns = encoder.get_feature_names_out(categorical_features)

encoded_df = pd.DataFrame(
    encoded_data,
    columns=encoded_columns,
    index=ml_df.index
)

print("Encoded shape:", encoded_df.shape)
print(encoded_df.head())

Encoded shape: (5403, 28)
   Product Name_Everlasting Gobstopper  Product Name_Fizzy Lifting Drinks  \
0                                  0.0                                0.0
1                                  0.0                                0.0
2                                  0.0                                0.0
3                                  0.0                                0.0
4                                  0.0                                0.0

   Product Name_Fun Dip  Product Name_Hair Toffee  Product Name_Kazookles  \
0                   0.0                       0.0                     0.0
1                   0.0                       0.0                     0.0
2                   0.0                       0.0                     0.0
3                   0.0                       0.0                     0.0
4                   0.0                       0.0                     0.0

   Product Name_Laffy Taffy  Product Name_Lickable Wallpaper  \
0                       0.0                              0.0
1                       0.0                              0.0
2                       0.0                              0.0
3                       0.0                              0.0
4                       0.0                              0.0

   Product Name_Nerds  Product Name_SweeTARTS  \
0                 0.0                     0.0
1                 0.0                     0.0
2                 0.0                     0.0
3                 0.0                     0.0
4                 0.0                     0.0

   Product Name_Wonka Bar - Fudge Mallows  ...  Factory_The Other Factory  \
0                                     0.0  ...                        0.0
1                                     0.0  ...                        0.0
2                                     0.0  ...                        0.0
3                                     0.0  ...                        0.0
4                                     0.0  ...                        0.0

   Factory_Wicked Choccy's  Region_Atlantic  Region_Gulf  Region_Interior  \
0                      1.0              0.0          0.0              1.0
1                      1.0              0.0          0.0              1.0
2                      0.0              0.0          0.0              1.0
3                      0.0              0.0          0.0              1.0
4                      1.0              1.0          0.0              0.0

   Region_Pacific  Ship Mode_First Class  Ship Mode_Same Day  \
0             0.0                    0.0                 0.0
1             0.0                    0.0                 0.0
2             0.0                    0.0                 0.0
3             0.0                    0.0                 0.0
4             0.0                    0.0                 0.0

   Ship Mode_Second Class  Ship Mode_Standard Class
0                     0.0                       1.0
1                     0.0                       1.0
2                     0.0                       1.0
3                     0.0                       1.0
4                     0.0                       1.0

[5 rows x 28 columns]

In [ ]:
# Combine encoded features with numerical features
X = pd.concat(
    [
        encoded_df,
        ml_df[["Order_Month", "Order_Year"]]
    ],
    axis=1
)

# Target variable
y = ml_df["Lead_Time_Days"]

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nFeature columns:")
print(X.columns.tolist())

X shape: (5403, 30)
y shape: (5403,)

Feature columns:
['Product Name_Everlasting Gobstopper', 'Product Name_Fizzy Lifting Drinks', 'Product Name_Fun Dip', 'Product Name_Hair Toffee', 'Product Name_Kazookles', 'Product Name_Laffy Taffy', 'Product Name_Lickable Wallpaper', 'Product Name_Nerds', 'Product Name_SweeTARTS', 'Product Name_Wonka Bar - Fudge Mallows', 'Product Name_Wonka Bar - Milk Chocolate', 'Product Name_Wonka Bar - Nutty Crunch Surprise', 'Product Name_Wonka Bar - Triple Dazzle Caramel', 'Product Name_Wonka Bar -Scrumdiddlyumptious', 'Product Name_Wonka Gum', "Factory_Lot's O' Nuts", 'Factory_Secret Factory', 'Factory_Sugar Shack', 'Factory_The Other Factory', "Factory_Wicked Choccy's", 'Region_Atlantic', 'Region_Gulf', 'Region_Interior', 'Region_Pacific', 'Ship Mode_First Class', 'Ship Mode_Same Day', 'Ship Mode_Second Class', 'Ship Mode_Standard Class', 'Order_Month', 'Order_Year']

In [ ]:
print("Earliest Order Date:", ml_df["Order Date"].min())
print("Latest Order Date:", ml_df["Order Date"].max())

print("\nOrder Year distribution:")
print(ml_df["Order_Year"].value_counts().sort_index())

Earliest Order Date: 2024-01-02 00:00:00
Latest Order Date: 2025-12-08 00:00:00

Order Year distribution:
Order_Year
2024.0    1668
2025.0     503
Name: count, dtype: int64

In [ ]:
print("Missing Order Date:", ml_df["Order Date"].isna().sum())
print("Missing Order Year:", ml_df["Order_Year"].isna().sum())
print("Missing Order Month:", ml_df["Order_Month"].isna().sum())
print("Missing Lead Time:", ml_df["Lead_Time_Days"].isna().sum())

Missing Order Date: 3232
Missing Order Year: 3232
Missing Order Month: 3232
Missing Lead Time: 3232

In [ ]:
print(ml_df[["Order Date", "Ship Date", "Product Name", "Factory"]].isna().sum())

print("\nRows with missing Order Date:")
print(ml_df[ml_df["Order Date"].isna()][
    ["Order Date", "Ship Date", "Product Name", "Factory"]
].head(10))

Order Date      3232
Ship Date          0
Product Name       0
Factory            0
dtype: int64

Rows with missing Order Date:
   Order Date  Ship Date                       Product Name            Factory
21        NaT 2026-07-11         Wonka Bar - Milk Chocolate    Wicked Choccy's
22        NaT 2026-07-09  Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts
23        NaT 2026-07-11         Wonka Bar - Milk Chocolate    Wicked Choccy's
24        NaT 2026-07-11     Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts
25        NaT 2026-07-08  Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's
26        NaT 2026-07-08                          Kazookles  The Other Factory
27        NaT 2026-07-08         Wonka Bar - Milk Chocolate    Wicked Choccy's
28        NaT 2026-07-11     Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts
29        NaT 2026-07-08         Wonka Bar - Milk Chocolate    Wicked Choccy's
30        NaT 2026-07-11  Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts

In [ ]:
# Check the original CSV values before date conversion

raw_df = pd.read_csv("/content/Nassau Candy Distributor.csv")

print("Raw Order Date missing:", raw_df["Order Date"].isna().sum())

print("\nSample raw Order Date values:")
print(raw_df["Order Date"].head(40).to_string())

print("\nRaw Order Date data type:")
print(raw_df["Order Date"].dtype)

Raw Order Date missing: 0

Sample raw Order Date values:
0     03-01-2024
1     04-01-2024
2     04-01-2024
3     04-01-2024
4     05-01-2024
5     06-01-2024
6     06-01-2024
7     06-01-2024
8     06-01-2024
9     06-01-2024
10    06-01-2024
11    06-01-2024
12    06-01-2024
13    06-01-2024
14    07-01-2024
15    07-01-2024
16    09-01-2024
17    09-01-2024
18    10-01-2024
19    10-01-2024
20    11-01-2024
21    13-01-2024
22    13-01-2024
23    13-01-2024
24    13-01-2024
25    13-01-2024
26    13-01-2024
27    13-01-2024
28    13-01-2024
29    13-01-2024
30    13-01-2024
31    13-01-2024
32    14-01-2024
33    15-01-2024
34    16-01-2024
35    16-01-2024
36    16-01-2024
37    16-01-2024
38    18-01-2024
39    19-01-2024

Raw Order Date data type:
object

In [ ]:
# Reload the original dataset
df = pd.read_csv("/content/Nassau Candy Distributor.csv")

# Correctly parse dates as DD-MM-YYYY
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

# Calculate Lead Time
df["Lead_Time_Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print("Missing Order Date:", df["Order Date"].isna().sum())
print("Missing Ship Date:", df["Ship Date"].isna().sum())
print("Missing Lead Time:", df["Lead_Time_Days"].isna().sum())

print("\nLead Time Summary:")
print(df["Lead_Time_Days"].describe())

Missing Order Date: 0
Missing Ship Date: 0
Missing Lead Time: 0

Lead Time Summary:
count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead_Time_Days, dtype: float64

In [ ]:
factory_mapping = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

df["Factory"] = df["Product Name"].map(factory_mapping)

print("Total rows:", len(df))
print("Mapped Factory:", df["Factory"].notna().sum())
print("Missing Factory:", df["Factory"].isna().sum())

print("\nFactory distribution:")
print(df["Factory"].value_counts())

Total rows: 10194
Mapped Factory: 10194
Missing Factory: 0

Factory distribution:
Factory
Lot's O' Nuts        5692
Wicked Choccy's      4152
Secret Factory        217
The Other Factory     100
Sugar Shack            33
Name: count, dtype: int64

In [ ]:
# Calculate missing date components first
df["Order_Month"] = df["Order Date"].dt.month
df["Order_Year"] = df["Order Date"].dt.year

# Create the ML dataset
ml_df = df[
    [
        "Product Name",
        "Factory",
        "Region",
        "Ship Mode",
        "Order_Month",
        "Order_Year",
        "Lead_Time_Days"
    ]
].copy()

print("ML dataset shape:", ml_df.shape)
print("\nMissing values:")
print(ml_df.isna().sum())
print("\nSample:")
print(ml_df.head())

ML dataset shape: (10194, 7)

Missing values:
Product Name      0
Factory           0
Region            0
Ship Mode         0
Order_Month       0
Order_Year        0
Lead_Time_Days    0
dtype: int64

Sample:
                        Product Name          Factory    Region  \
0         Wonka Bar - Milk Chocolate  Wicked Choccy's  Interior
1  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's  Interior
2  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts  Interior
3     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts  Interior
4  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's  Atlantic

        Ship Mode  Order_Month  Order_Year  Lead_Time_Days
0  Standard Class            1        2024             909
1  Standard Class            1        2024             909
2  Standard Class            1        2024             909
3  Standard Class            1        2024             909
4  Standard Class            1        2024             912

In [ ]:
from sklearn.model_selection import train_test_split

# Features
X = ml_df[
    [
        "Product Name",
        "Factory",
        "Region",
        "Ship Mode",
        "Order_Month",
        "Order_Year"
    ]
]

# Target
y = ml_df["Lead_Time_Days"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

print("\nTraining features:", X_train.shape[1])
print("Testing features:", X_test.shape[1])

Training rows: 8155
Testing rows: 2039

Training features: 6
Testing features: 6

In [ ]:
from sklearn.preprocessing import OneHotEncoder

categorical_features = [
    "Product Name",
    "Factory",
    "Region",
    "Ship Mode"
]

# Create encoder
encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

# Fit ONLY on training data
X_train_encoded = encoder.fit_transform(
    X_train[categorical_features]
)

# Transform test data using the same encoder
X_test_encoded = encoder.transform(
    X_test[categorical_features]
)

# Get encoded column names
encoded_columns = encoder.get_feature_names_out(
    categorical_features
)

print("Encoded training shape:", X_train_encoded.shape)
print("Encoded testing shape:", X_test_encoded.shape)

print("\nEncoded features:")
print(list(encoded_columns))

Encoded training shape: (8155, 28)
Encoded testing shape: (2039, 28)

Encoded features:
['Product Name_Everlasting Gobstopper', 'Product Name_Fizzy Lifting Drinks', 'Product Name_Fun Dip', 'Product Name_Hair Toffee', 'Product Name_Kazookles', 'Product Name_Laffy Taffy', 'Product Name_Lickable Wallpaper', 'Product Name_Nerds', 'Product Name_SweeTARTS', 'Product Name_Wonka Bar - Fudge Mallows', 'Product Name_Wonka Bar - Milk Chocolate', 'Product Name_Wonka Bar - Nutty Crunch Surprise', 'Product Name_Wonka Bar - Triple Dazzle Caramel', 'Product Name_Wonka Bar -Scrumdiddlyumptious', 'Product Name_Wonka Gum', "Factory_Lot's O' Nuts", 'Factory_Secret Factory', 'Factory_Sugar Shack', 'Factory_The Other Factory', "Factory_Wicked Choccy's", 'Region_Atlantic', 'Region_Gulf', 'Region_Interior', 'Region_Pacific', 'Ship Mode_First Class', 'Ship Mode_Same Day', 'Ship Mode_Second Class', 'Ship Mode_Standard Class']

In [ ]:
import pandas as pd

# Convert encoded arrays into DataFrames
X_train_encoded_df = pd.DataFrame(
    X_train_encoded,
    columns=encoded_columns,
    index=X_train.index
)

X_test_encoded_df = pd.DataFrame(
    X_test_encoded,
    columns=encoded_columns,
    index=X_test.index
)

# Add numerical features
X_train_final = pd.concat(
    [
        X_train_encoded_df,
        X_train[["Order_Month", "Order_Year"]]
    ],
    axis=1
)

X_test_final = pd.concat(
    [
        X_test_encoded_df,
        X_test[["Order_Month", "Order_Year"]]
    ],
    axis=1
)

print("Final training shape:", X_train_final.shape)
print("Final testing shape:", X_test_final.shape)

print("\nTotal features:", X_train_final.shape[1])

Final training shape: (8155, 30)
Final testing shape: (2039, 30)

Total features: 30

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
import pandas as pd

# Ensure ml_df and other preparation variables are defined
if 'ml_df' not in globals():
    # Reload raw dataset
    df = pd.read_csv("/content/Nassau Candy Distributor.csv")

    # Correctly parse dates as DD-MM-YYYY
    df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d-%m-%Y")
    df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d-%m-%Y")

    # Calculate Lead Time
    df["Lead_Time_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

    # Map Products to Factories
    factory_mapping = {
        "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
        "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
        "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
        "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
        "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
        "Laffy Taffy": "Sugar Shack",
        "SweeTARTS": "Sugar Shack",
        "Nerds": "Sugar Shack",
        "Fun Dip": "Sugar Shack",
        "Fizzy Lifting Drinks": "Sugar Shack",
        "Everlasting Gobstopper": "Secret Factory",
        "Hair Toffee": "The Other Factory",
        "Lickable Wallpaper": "Secret Factory",
        "Wonka Gum": "Secret Factory",
        "Kazookles": "The Other Factory"
    }
    df["Factory"] = df["Product Name"].map(factory_mapping)
    df["Order_Month"] = df["Order Date"].dt.month
    df["Order_Year"] = df["Order Date"].dt.year

    # Create ML dataframe
    ml_df = df[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year", "Lead_Time_Days"]].copy()

if 'X_train' not in globals() or 'X_test' not in globals():
    from sklearn.model_selection import train_test_split
    X = ml_df[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year"]]
    y = ml_df["Lead_Time_Days"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

if 'X_train_final' not in globals() or 'X_test_final' not in globals():
    from sklearn.preprocessing import OneHotEncoder
    categorical_features = ["Product Name", "Factory", "Region", "Ship Mode"]
    encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

    X_train_encoded = encoder.fit_transform(X_train[categorical_features])
    X_test_encoded = encoder.transform(X_test[categorical_features])
    encoded_columns = encoder.get_feature_names_out(categorical_features)

    X_train_encoded_df = pd.DataFrame(X_train_encoded, columns=encoded_columns, index=X_train.index)
    X_test_encoded_df = pd.DataFrame(X_test_encoded, columns=encoded_columns, index=X_test.index)

    X_train_final = pd.concat([X_train_encoded_df, X_train[["Order_Month", "Order_Year"]]], axis=1)
    X_test_final = pd.concat([X_test_encoded_df, X_test[["Order_Month", "Order_Year"]]], axis=1)

# Create Linear Regression model
lr_model = LinearRegression()

# Train the model
lr_model.fit(X_train_final, y_train)

# Predict on test data
lr_predictions = lr_model.predict(X_test_final)

# Evaluate the model
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_predictions))
lr_mae = mean_absolute_error(y_test, lr_predictions)
lr_r2 = r2_score(y_test, lr_predictions)

print("Linear Regression Results")
print("-------------------------")
print("RMSE:", round(lr_rmse, 2))
print("MAE :", round(lr_mae, 2))
print("R²  :", round(lr_r2, 4))

Linear Regression Results
-------------------------
RMSE: 182.45
MAE : 181.43
R²  : 0.5293

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Create Random Forest model
rf_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

# Train the model
rf_model.fit(X_train_final, y_train)

# Predict
rf_predictions = rf_model.predict(X_test_final)

# Evaluate
rf_rmse = np.sqrt(
    mean_squared_error(y_test, rf_predictions)
)

rf_mae = mean_absolute_error(
    y_test,
    rf_predictions
)

rf_r2 = r2_score(
    y_test,
    rf_predictions
)

print("Random Forest Results")
print("---------------------")
print("RMSE:", round(rf_rmse, 2))
print("MAE :", round(rf_mae, 2))
print("R²  :", round(rf_r2, 4))

Random Forest Results
---------------------
RMSE: 192.37
MAE : 172.72
R²  : 0.4767

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

# Create Gradient Boosting model
gb_model = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

# Train
gb_model.fit(X_train_final, y_train)

# Predict
gb_predictions = gb_model.predict(X_test_final)

# Evaluate
gb_rmse = np.sqrt(
    mean_squared_error(y_test, gb_predictions)
)

gb_mae = mean_absolute_error(
    y_test,
    gb_predictions
)

gb_r2 = r2_score(
    y_test,
    gb_predictions
)

print("Gradient Boosting Results")
print("-------------------------")
print("RMSE:", round(gb_rmse, 2))
print("MAE :", round(gb_mae, 2))
print("R²  :", round(gb_r2, 4))

Gradient Boosting Results
-------------------------
RMSE: 181.65
MAE : 179.94
R²  : 0.5334

In [ ]:
model_comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "RMSE": [
        lr_rmse,
        rf_rmse,
        gb_rmse
    ],
    "MAE": [
        lr_mae,
        rf_mae,
        gb_mae
    ],
    "R2": [
        lr_r2,
        rf_r2,
        gb_r2
    ]
})

model_comparison = model_comparison.round(4)

print(model_comparison)

               Model      RMSE       MAE      R2
0  Linear Regression  182.4549  181.4319  0.5293
1      Random Forest  192.3689  172.7162  0.4767
2  Gradient Boosting  181.6532  179.9391  0.5334

In [ ]:
# Get feature importance from Gradient Boosting

feature_importance = pd.DataFrame({
    "Feature": X_train_final.columns,
    "Importance": gb_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print("Top 15 Important Features:")
print(feature_importance.head(15).to_string(index=False))

Top 15 Important Features:
                                       Feature  Importance
                                    Order_Year    0.974881
                                   Order_Month    0.007604
                                   Region_Gulf    0.004101
                               Region_Atlantic    0.003635
                               Region_Interior    0.001862
                         Ship Mode_First Class    0.001379
                                Region_Pacific    0.001266
                        Ship Mode_Second Class    0.000875
                        Factory_Secret Factory    0.000773
Product Name_Wonka Bar - Nutty Crunch Surprise    0.000716
                            Ship Mode_Same Day    0.000710
                          Product Name_Fun Dip    0.000389
                      Ship Mode_Standard Class    0.000303
                            Product Name_Nerds    0.000229
               Product Name_Lickable Wallpaper    0.000193

In [ ]:
import pandas as pd

# Convert date columns to datetime
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d-%m-%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d-%m-%Y")

# Create missing columns required for the grouping
df["Order_Year"] = df["Order Date"].dt.year
df["Lead_Time_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

# Perform year-wise analysis
year_analysis = df.groupby("Order_Year")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).reset_index()

print(year_analysis)

   Order_Year  count         mean  median   min   max
0        2024   4181  1094.018417  1269.0   904  1277
1        2025   6013  1478.558290  1637.0  1269  1642

In [ ]:
df["Ship_Year"] = df["Ship Date"].dt.year

df["Year_Gap"] = df["Ship_Year"] - df["Order_Year"]

year_gap_analysis = df.groupby("Order_Year")["Year_Gap"].agg(
    ["count", "mean", "median", "min", "max"]
).reset_index()

print(year_gap_analysis)

   Order_Year  count      mean  median  min  max
0        2024   4181  3.160249     3.0    2    4
1        2025   6013  4.189922     4.0    3    5

In [ ]:
# Define the factory mapping dictionary
factory_mapping = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

# Map products to factories
df["Factory"] = df["Product Name"].map(factory_mapping)

# Perform factory-wise lead time analysis
factory_analysis = df.groupby("Factory")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean")

print(factory_analysis)

                   count         mean  median  min   max
Factory
The Other Factory    100  1280.280000  1273.0  904  1641
Wicked Choccy's     4152  1321.082129  1274.0  904  1642
Lot's O' Nuts       5692  1321.228742  1274.0  904  1642
Secret Factory       217  1321.870968  1274.0  904  1642
Sugar Shack           33  1340.030303  1274.0  907  1642

In [ ]:
region_analysis = df.groupby("Region")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean")

print(region_analysis)

          count         mean  median  min   max
Region
Gulf       1620  1311.374691  1274.0  904  1642
Pacific    3253  1322.194897  1274.0  904  1642
Atlantic   2986  1322.745144  1274.0  904  1642
Interior   2335  1323.091221  1274.0  904  1642

In [ ]:
product_analysis = df.groupby("Product Name")["Lead_Time_Days"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean")

print(product_analysis)

                                   count         mean  median   min   max
Product Name
Fun Dip                                3  1272.666667  1272.0  1271  1275
Kazookles                             96  1272.989583  1273.0   904  1641
Fizzy Lifting Drinks                   6  1273.500000  1274.0   907  1640
Nerds                                  4  1274.000000  1274.0   908  1640
Wonka Gum                            120  1306.525000  1273.5   904  1642
Wonka Bar - Fudge Mallows           1818  1314.242024  1274.0   904  1642
Wonka Bar - Milk Chocolate          2137  1316.764623  1274.0   904  1642
Wonka Bar -Scrumdiddlyumptious      2064  1320.641957  1274.0   904  1642
Wonka Bar - Triple Dazzle Caramel   2015  1325.661042  1274.0   904  1642
Wonka Bar - Nutty Crunch Surprise   1810  1328.915470  1274.0   904  1642
Lickable Wallpaper                    94  1339.138298  1274.0   904  1641
Laffy Taffy                           10  1383.100000  1275.0   909  1642
SweeTARTS                             10  1383.500000  1274.0   910  1641
Everlasting Gobstopper                 3  1394.666667  1273.0  1270  1641
Hair Toffee                            4  1455.250000  1455.0  1272  1639

In [ ]:
product_region_analysis = df.groupby(
    ["Product Name", "Region"]
)["Lead_Time_Days"].agg(
    ["count", "mean", "median"]
).reset_index()

print(product_region_analysis)

                         Product Name    Region  count         mean  median
0              Everlasting Gobstopper      Gulf      1  1273.000000  1273.0
1              Everlasting Gobstopper  Interior      1  1641.000000  1641.0
2              Everlasting Gobstopper   Pacific      1  1270.000000  1270.0
3                Fizzy Lifting Drinks  Atlantic      2  1455.500000  1455.5
4                Fizzy Lifting Drinks      Gulf      1   909.000000   909.0
5                Fizzy Lifting Drinks  Interior      2  1273.500000  1273.5
6                Fizzy Lifting Drinks   Pacific      1  1274.000000  1274.0
7                             Fun Dip  Atlantic      1  1275.000000  1275.0
8                             Fun Dip      Gulf      1  1272.000000  1272.0
9                             Fun Dip  Interior      1  1271.000000  1271.0
10                        Hair Toffee  Atlantic      1  1639.000000  1639.0
11                        Hair Toffee      Gulf      1  1635.000000  1635.0
12                        Hair Toffee   Pacific      2  1273.500000  1273.5
13                          Kazookles  Atlantic     37  1273.108108  1273.0
14                          Kazookles      Gulf     18  1252.500000  1273.0
15                          Kazookles  Interior     11  1206.636364  1273.0
16                          Kazookles   Pacific     30  1309.466667  1273.0
17                        Laffy Taffy  Atlantic      6  1456.166667  1455.0
18                        Laffy Taffy      Gulf      2  1092.000000  1092.0
19                        Laffy Taffy  Interior      1  1272.000000  1272.0
20                        Laffy Taffy   Pacific      1  1638.000000  1638.0
21                 Lickable Wallpaper  Atlantic     35  1387.828571  1275.0
22                 Lickable Wallpaper      Gulf     10  1309.500000  1273.5
23                 Lickable Wallpaper  Interior     15  1321.466667  1274.0
24                 Lickable Wallpaper   Pacific     34  1305.529412  1273.5
25                              Nerds  Atlantic      4  1274.000000  1274.0
26                          SweeTARTS  Atlantic      5  1347.600000  1275.0
27                          SweeTARTS  Interior      4  1364.750000  1273.0
28                          SweeTARTS   Pacific      1  1638.000000  1638.0
29          Wonka Bar - Fudge Mallows  Atlantic    548  1321.171533  1273.0
30          Wonka Bar - Fudge Mallows      Gulf    291  1304.580756  1273.0
31          Wonka Bar - Fudge Mallows  Interior    410  1311.570732  1273.0
32          Wonka Bar - Fudge Mallows   Pacific    569  1314.434095  1274.0
33         Wonka Bar - Milk Chocolate  Atlantic    639  1309.320814  1274.0
34         Wonka Bar - Milk Chocolate      Gulf    333  1289.732733  1274.0
35         Wonka Bar - Milk Chocolate  Interior    499  1331.977956  1274.0
36         Wonka Bar - Milk Chocolate   Pacific    666  1326.024024  1274.0
37  Wonka Bar - Nutty Crunch Surprise  Atlantic    490  1360.426531  1274.0
38  Wonka Bar - Nutty Crunch Surprise      Gulf    296  1322.614865  1274.0
39  Wonka Bar - Nutty Crunch Surprise  Interior    452  1329.847345  1274.0
40  Wonka Bar - Nutty Crunch Surprise   Pacific    572  1304.445804  1273.0
41  Wonka Bar - Triple Dazzle Caramel  Atlantic    558  1323.578853  1274.0
42  Wonka Bar - Triple Dazzle Caramel      Gulf    330  1328.669697  1274.0
43  Wonka Bar - Triple Dazzle Caramel  Interior    451  1316.334812  1274.0
44  Wonka Bar - Triple Dazzle Caramel   Pacific    676  1332.133136  1274.0
45     Wonka Bar -Scrumdiddlyumptious  Atlantic    623  1305.370787  1273.0
46     Wonka Bar -Scrumdiddlyumptious      Gulf    310  1314.545161  1274.0
47     Wonka Bar -Scrumdiddlyumptious  Interior    459  1329.908497  1274.0
48     Wonka Bar -Scrumdiddlyumptious   Pacific    672  1331.282738  1274.0
49                          Wonka Gum  Atlantic     37  1312.756757  1273.0
50                          Wonka Gum      Gulf     26  1343.692308  1275.0
51                          Wonka Gum  Interior     29  1260.206897  1273.0
52                          Wonka Gum   Pacific     28  1311.750000  1274.0

In [ ]:
reliable_combinations = product_region_analysis[
    product_region_analysis["count"] >= 30
].sort_values("mean", ascending=False)

print(reliable_combinations)

                         Product Name    Region  count         mean  median
21                 Lickable Wallpaper  Atlantic     35  1387.828571  1275.0
37  Wonka Bar - Nutty Crunch Surprise  Atlantic    490  1360.426531  1274.0
44  Wonka Bar - Triple Dazzle Caramel   Pacific    676  1332.133136  1274.0
35         Wonka Bar - Milk Chocolate  Interior    499  1331.977956  1274.0
48     Wonka Bar -Scrumdiddlyumptious   Pacific    672  1331.282738  1274.0
47     Wonka Bar -Scrumdiddlyumptious  Interior    459  1329.908497  1274.0
39  Wonka Bar - Nutty Crunch Surprise  Interior    452  1329.847345  1274.0
42  Wonka Bar - Triple Dazzle Caramel      Gulf    330  1328.669697  1274.0
36         Wonka Bar - Milk Chocolate   Pacific    666  1326.024024  1274.0
41  Wonka Bar - Triple Dazzle Caramel  Atlantic    558  1323.578853  1274.0
38  Wonka Bar - Nutty Crunch Surprise      Gulf    296  1322.614865  1274.0
29          Wonka Bar - Fudge Mallows  Atlantic    548  1321.171533  1273.0
43  Wonka Bar - Triple Dazzle Caramel  Interior    451  1316.334812  1274.0
46     Wonka Bar -Scrumdiddlyumptious      Gulf    310  1314.545161  1274.0
32          Wonka Bar - Fudge Mallows   Pacific    569  1314.434095  1274.0
49                          Wonka Gum  Atlantic     37  1312.756757  1273.0
31          Wonka Bar - Fudge Mallows  Interior    410  1311.570732  1273.0
16                          Kazookles   Pacific     30  1309.466667  1273.0
33         Wonka Bar - Milk Chocolate  Atlantic    639  1309.320814  1274.0
24                 Lickable Wallpaper   Pacific     34  1305.529412  1273.5
45     Wonka Bar -Scrumdiddlyumptious  Atlantic    623  1305.370787  1273.0
30          Wonka Bar - Fudge Mallows      Gulf    291  1304.580756  1273.0
40  Wonka Bar - Nutty Crunch Surprise   Pacific    572  1304.445804  1273.0
34         Wonka Bar - Milk Chocolate      Gulf    333  1289.732733  1274.0
13                          Kazookles  Atlantic     37  1273.108108  1273.0

In [ ]:
print(df["Lead_Time_Days"].describe())

print("\nLead Time Value Counts:")
print(df["Lead_Time_Days"].value_counts().sort_index().head(20))

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead_Time_Days, dtype: float64

Lead Time Value Counts:
Lead_Time_Days
904       89
905       40
906      289
907      176
908      591
909      519
910      207
911      134
912        4
915        2
1269     258
1270     156
1271     610
1272     456
1273    1326
1274    1035
1275     612
1276     293
1277      18
1634       3
Name: count, dtype: int64

In [ ]:
df["Lead_Time_Group"] = pd.cut(
    df["Lead_Time_Days"],
    bins=[0, 1000, 1500, 2000],
    labels=["Short", "Medium", "Long"]
)

cluster_year = pd.crosstab(
    df["Order_Year"],
    df["Lead_Time_Group"],
    normalize="index"
) * 100

print(cluster_year.round(2))

Lead_Time_Group  Short  Medium   Long
Order_Year
2024             49.06   50.94   0.00
2025              0.00   43.81  56.19

In [ ]:
product_factory = df.groupby(
    ["Product Name", "Factory"]
).size().reset_index(name="count")

print(product_factory)

                         Product Name            Factory  count
0              Everlasting Gobstopper     Secret Factory      3
1                Fizzy Lifting Drinks        Sugar Shack      6
2                             Fun Dip        Sugar Shack      3
3                         Hair Toffee  The Other Factory      4
4                           Kazookles  The Other Factory     96
5                         Laffy Taffy        Sugar Shack     10
6                  Lickable Wallpaper     Secret Factory     94
7                               Nerds        Sugar Shack      4
8                           SweeTARTS        Sugar Shack     10
9           Wonka Bar - Fudge Mallows      Lot's O' Nuts   1818
10         Wonka Bar - Milk Chocolate    Wicked Choccy's   2137
11  Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts   1810
12  Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's   2015
13     Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts   2064
14                          Wonka Gum     Secret Factory    120

In [ ]:
product_region = df.groupby(
    ["Product Name", "Region"]
).size().reset_index(name="count")

print(product_region)

                         Product Name    Region  count
0              Everlasting Gobstopper      Gulf      1
1              Everlasting Gobstopper  Interior      1
2              Everlasting Gobstopper   Pacific      1
3                Fizzy Lifting Drinks  Atlantic      2
4                Fizzy Lifting Drinks      Gulf      1
5                Fizzy Lifting Drinks  Interior      2
6                Fizzy Lifting Drinks   Pacific      1
7                             Fun Dip  Atlantic      1
8                             Fun Dip      Gulf      1
9                             Fun Dip  Interior      1
10                        Hair Toffee  Atlantic      1
11                        Hair Toffee      Gulf      1
12                        Hair Toffee   Pacific      2
13                          Kazookles  Atlantic     37
14                          Kazookles      Gulf     18
15                          Kazookles  Interior     11
16                          Kazookles   Pacific     30
17                        Laffy Taffy  Atlantic      6
18                        Laffy Taffy      Gulf      2
19                        Laffy Taffy  Interior      1
20                        Laffy Taffy   Pacific      1
21                 Lickable Wallpaper  Atlantic     35
22                 Lickable Wallpaper      Gulf     10
23                 Lickable Wallpaper  Interior     15
24                 Lickable Wallpaper   Pacific     34
25                              Nerds  Atlantic      4
26                          SweeTARTS  Atlantic      5
27                          SweeTARTS  Interior      4
28                          SweeTARTS   Pacific      1
29          Wonka Bar - Fudge Mallows  Atlantic    548
30          Wonka Bar - Fudge Mallows      Gulf    291
31          Wonka Bar - Fudge Mallows  Interior    410
32          Wonka Bar - Fudge Mallows   Pacific    569
33         Wonka Bar - Milk Chocolate  Atlantic    639
34         Wonka Bar - Milk Chocolate      Gulf    333
35         Wonka Bar - Milk Chocolate  Interior    499
36         Wonka Bar - Milk Chocolate   Pacific    666
37  Wonka Bar - Nutty Crunch Surprise  Atlantic    490
38  Wonka Bar - Nutty Crunch Surprise      Gulf    296
39  Wonka Bar - Nutty Crunch Surprise  Interior    452
40  Wonka Bar - Nutty Crunch Surprise   Pacific    572
41  Wonka Bar - Triple Dazzle Caramel  Atlantic    558
42  Wonka Bar - Triple Dazzle Caramel      Gulf    330
43  Wonka Bar - Triple Dazzle Caramel  Interior    451
44  Wonka Bar - Triple Dazzle Caramel   Pacific    676
45     Wonka Bar -Scrumdiddlyumptious  Atlantic    623
46     Wonka Bar -Scrumdiddlyumptious      Gulf    310
47     Wonka Bar -Scrumdiddlyumptious  Interior    459
48     Wonka Bar -Scrumdiddlyumptious   Pacific    672
49                          Wonka Gum  Atlantic     37
50                          Wonka Gum      Gulf     26
51                          Wonka Gum  Interior     29
52                          Wonka Gum   Pacific     28

In [ ]:
factory_region_analysis = df.groupby(
    ["Factory", "Region"]
)["Lead_Time_Days"].agg(
    ["count", "mean", "median"]
).reset_index()

print(factory_region_analysis)

              Factory    Region  count         mean  median
0       Lot's O' Nuts  Atlantic   1661  1326.825406  1274.0
1       Lot's O' Nuts      Gulf    897  1313.975474  1274.0
2       Lot's O' Nuts  Interior   1321  1324.196064  1274.0
3       Lot's O' Nuts   Pacific   1813  1317.527854  1274.0
4      Secret Factory  Atlantic     72  1349.250000  1275.0
5      Secret Factory      Gulf     37  1332.540541  1274.0
6      Secret Factory  Interior     45  1289.088889  1273.0
7      Secret Factory   Pacific     63  1307.730159  1274.0
8         Sugar Shack  Atlantic     18  1375.388889  1275.0
9         Sugar Shack      Gulf      4  1091.250000  1090.5
10        Sugar Shack  Interior      8  1318.625000  1272.5
11        Sugar Shack   Pacific      3  1516.666667  1638.0
12  The Other Factory  Atlantic     38  1282.736842  1273.0
13  The Other Factory      Gulf     19  1272.631579  1273.0
14  The Other Factory  Interior     11  1206.636364  1273.0
15  The Other Factory   Pacific     32  1307.218750  1273.0
16    Wicked Choccy's  Atlantic   1197  1315.967419  1274.0
17    Wicked Choccy's      Gulf    663  1309.113122  1274.0
18    Wicked Choccy's  Interior    950  1324.551579  1274.0
19    Wicked Choccy's   Pacific   1342  1329.101341  1274.0

In [ ]:
print(df[["Country/Region", "City", "State/Province", "Postal Code", "Region"]].head())

  Country/Region          City State/Province Postal Code    Region
0  United States       Houston          Texas       77095  Interior
1  United States    Naperville       Illinois       60540  Interior
2  United States    Naperville       Illinois       60540  Interior
3  United States    Naperville       Illinois       60540  Interior
4  United States  Philadelphia   Pennsylvania       19143  Atlantic

In [ ]:
print("Unique Cities:", df["City"].nunique())
print("Unique States:", df["State/Province"].nunique())
print("Unique Postal Codes:", df["Postal Code"].nunique())

Unique Cities: 542
Unique States: 59
Unique Postal Codes: 654

In [ ]:
print(df["Postal Code"].dtype)
print(df["Postal Code"].head(10))
print("Missing Postal Codes:", df["Postal Code"].isna().sum())

object
0    77095
1    60540
2    60540
3    60540
4    19143
5    42420
6    42420
7    30605
8    42420
9    42420
Name: Postal Code, dtype: object
Missing Postal Codes: 0

In [ ]:
region_year_analysis = df.groupby(
    ["Order_Year", "Region"]
)["Lead_Time_Days"].agg(
    ["count", "mean", "median"]
).reset_index()

print(region_year_analysis)

   Order_Year    Region  count         mean  median
0        2024  Atlantic   1224  1105.968954  1271.0
1        2024      Gulf    689  1088.298984   911.0
2        2024  Interior    942  1092.600849  1269.0
3        2024   Pacific   1326  1086.966063   911.0
4        2025  Atlantic   1762  1473.332009  1637.0
5        2025      Gulf    931  1476.465091  1636.0
6        2025  Interior   1393  1478.957645  1636.0
7        2025   Pacific   1927  1484.059678  1636.0

In [ ]:
factory_lead_group = pd.crosstab(
    df["Factory"],
    df["Lead_Time_Group"]
)

print(factory_lead_group)

Lead_Time_Group    Short  Medium  Long
Factory
Lot's O' Nuts       1134    2676  1882
Secret Factory        55      78    84
Sugar Shack            6      15    12
The Other Factory     24      50    26
Wicked Choccy's      832    1945  1375

In [ ]:
product_lead_group = pd.crosstab(
    df["Product Name"],
    df["Lead_Time_Group"]
)

print(product_lead_group)

Lead_Time_Group                    Short  Medium  Long
Product Name
Everlasting Gobstopper                 0       2     1
Fizzy Lifting Drinks                   2       2     2
Fun Dip                                0       3     0
Hair Toffee                            0       2     2
Kazookles                             24      48    24
Laffy Taffy                            1       5     4
Lickable Wallpaper                    22      33    39
Nerds                                  2       0     2
SweeTARTS                              1       5     4
Wonka Bar - Fudge Mallows            384     846   588
Wonka Bar - Milk Chocolate           444     995   698
Wonka Bar - Nutty Crunch Surprise    344     846   620
Wonka Bar - Triple Dazzle Caramel    388     950   677
Wonka Bar -Scrumdiddlyumptious       406     984   674
Wonka Gum                             33      43    44

In [ ]:
factory_baseline = df.groupby(
    ["Product Name", "Factory"]
)["Lead_Time_Days"].agg(
    ["count", "mean", "median"]
).reset_index()

print(factory_baseline)

                         Product Name            Factory  count         mean  \
0              Everlasting Gobstopper     Secret Factory      3  1394.666667
1                Fizzy Lifting Drinks        Sugar Shack      6  1273.500000
2                             Fun Dip        Sugar Shack      3  1272.666667
3                         Hair Toffee  The Other Factory      4  1455.250000
4                           Kazookles  The Other Factory     96  1272.989583
5                         Laffy Taffy        Sugar Shack     10  1383.100000
6                  Lickable Wallpaper     Secret Factory     94  1339.138298
7                               Nerds        Sugar Shack      4  1274.000000
8                           SweeTARTS        Sugar Shack     10  1383.500000
9           Wonka Bar - Fudge Mallows      Lot's O' Nuts   1818  1314.242024
10         Wonka Bar - Milk Chocolate    Wicked Choccy's   2137  1316.764623
11  Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts   1810  1328.915470
12  Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's   2015  1325.661042
13     Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts   2064  1320.641957
14                          Wonka Gum     Secret Factory    120  1306.525000

    median
0   1273.0
1   1274.0
2   1272.0
3   1455.0
4   1273.0
5   1275.0
6   1274.0
7   1274.0
8   1274.0
9   1274.0
10  1274.0
11  1274.0
12  1274.0
13  1274.0
14  1273.5

In [ ]:
all_factories = df["Factory"].unique().tolist()

print("Available Factories:")
print(all_factories)

Available Factories:
["Wicked Choccy's", "Lot's O' Nuts", 'Secret Factory', 'The Other Factory', 'Sugar Shack']

In [ ]:
products = df["Product Name"].unique()
factories = df["Factory"].unique()

scenario_df = pd.MultiIndex.from_product(
    [products, factories],
    names=["Product Name", "Scenario Factory"]
).to_frame(index=False)

current_factory_map = df[
    ["Product Name", "Factory"]
].drop_duplicates()

current_factory_map = current_factory_map.rename(
    columns={"Factory": "Current Factory"}
)

scenario_df = scenario_df.merge(
    current_factory_map,
    on="Product Name",
    how="left"
)

scenario_df["Scenario Type"] = scenario_df.apply(
    lambda row: "Current"
    if row["Scenario Factory"] == row["Current Factory"]
    else "Alternative",
    axis=1
)

print(scenario_df.head(20))
print("\nTotal Scenarios:", len(scenario_df))

                         Product Name   Scenario Factory  Current Factory  \
0          Wonka Bar - Milk Chocolate    Wicked Choccy's  Wicked Choccy's
1          Wonka Bar - Milk Chocolate      Lot's O' Nuts  Wicked Choccy's
2          Wonka Bar - Milk Chocolate     Secret Factory  Wicked Choccy's
3          Wonka Bar - Milk Chocolate  The Other Factory  Wicked Choccy's
4          Wonka Bar - Milk Chocolate        Sugar Shack  Wicked Choccy's
5   Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's  Wicked Choccy's
6   Wonka Bar - Triple Dazzle Caramel      Lot's O' Nuts  Wicked Choccy's
7   Wonka Bar - Triple Dazzle Caramel     Secret Factory  Wicked Choccy's
8   Wonka Bar - Triple Dazzle Caramel  The Other Factory  Wicked Choccy's
9   Wonka Bar - Triple Dazzle Caramel        Sugar Shack  Wicked Choccy's
10  Wonka Bar - Nutty Crunch Surprise    Wicked Choccy's    Lot's O' Nuts
11  Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts    Lot's O' Nuts
12  Wonka Bar - Nutty Crunch Surprise     Secret Factory    Lot's O' Nuts
13  Wonka Bar - Nutty Crunch Surprise  The Other Factory    Lot's O' Nuts
14  Wonka Bar - Nutty Crunch Surprise        Sugar Shack    Lot's O' Nuts
15     Wonka Bar -Scrumdiddlyumptious    Wicked Choccy's    Lot's O' Nuts
16     Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts    Lot's O' Nuts
17     Wonka Bar -Scrumdiddlyumptious     Secret Factory    Lot's O' Nuts
18     Wonka Bar -Scrumdiddlyumptious  The Other Factory    Lot's O' Nuts
19     Wonka Bar -Scrumdiddlyumptious        Sugar Shack    Lot's O' Nuts

   Scenario Type
0        Current
1    Alternative
2    Alternative
3    Alternative
4    Alternative
5        Current
6    Alternative
7    Alternative
8    Alternative
9    Alternative
10   Alternative
11       Current
12   Alternative
13   Alternative
14   Alternative
15   Alternative
16       Current
17   Alternative
18   Alternative
19   Alternative

Total Scenarios: 75

In [ ]:
# Ensure date columns are parsed correctly
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d-%m-%Y")

# Recreate missing date component columns
df["Order_Month"] = df["Order Date"].dt.month
df["Order_Year"] = df["Order Date"].dt.year

scenario_base = df[
    [
        "Product Name",
        "Region",
        "Ship Mode",
        "Order_Month",
        "Order_Year",
        "Factory"
    ]
].copy()

scenario_base = scenario_base.rename(
    columns={"Factory": "Current Factory"}
)

print(scenario_base.head())
print("\nRows:", len(scenario_base))

                        Product Name    Region       Ship Mode  Order_Month  \
0         Wonka Bar - Milk Chocolate  Interior  Standard Class            1
1  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class            1
2  Wonka Bar - Nutty Crunch Surprise  Interior  Standard Class            1
3     Wonka Bar -Scrumdiddlyumptious  Interior  Standard Class            1
4  Wonka Bar - Triple Dazzle Caramel  Atlantic  Standard Class            1

   Order_Year  Current Factory
0        2024  Wicked Choccy's
1        2024  Wicked Choccy's
2        2024    Lot's O' Nuts
3        2024    Lot's O' Nuts
4        2024  Wicked Choccy's

Rows: 10194

In [ ]:
scenario_orders = scenario_base.merge(
    pd.DataFrame({"Scenario Factory": all_factories}),
    how="cross"
)

scenario_orders["Scenario Type"] = scenario_orders.apply(
    lambda row: "Current"
    if row["Scenario Factory"] == row["Current Factory"]
    else "Alternative",
    axis=1
)

print(scenario_orders.head(10))
print("\nTotal Scenario Rows:", len(scenario_orders))

                        Product Name    Region       Ship Mode  Order_Month  \
0         Wonka Bar - Milk Chocolate  Interior  Standard Class            1
1         Wonka Bar - Milk Chocolate  Interior  Standard Class            1
2         Wonka Bar - Milk Chocolate  Interior  Standard Class            1
3         Wonka Bar - Milk Chocolate  Interior  Standard Class            1
4         Wonka Bar - Milk Chocolate  Interior  Standard Class            1
5  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class            1
6  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class            1
7  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class            1
8  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class            1
9  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class            1

   Order_Year  Current Factory   Scenario Factory Scenario Type
0        2024  Wicked Choccy's    Wicked Choccy's       Current
1        2024  Wicked Choccy's      Lot's O' Nuts   Alternative
2        2024  Wicked Choccy's     Secret Factory   Alternative
3        2024  Wicked Choccy's  The Other Factory   Alternative
4        2024  Wicked Choccy's        Sugar Shack   Alternative
5        2024  Wicked Choccy's    Wicked Choccy's       Current
6        2024  Wicked Choccy's      Lot's O' Nuts   Alternative
7        2024  Wicked Choccy's     Secret Factory   Alternative
8        2024  Wicked Choccy's  The Other Factory   Alternative
9        2024  Wicked Choccy's        Sugar Shack   Alternative

Total Scenario Rows: 50970

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

# Fallback: Reconstruct and fit the encoder if it's missing from the active session
if 'encoder' not in globals() or 'encoded_columns' not in globals():
    # Re-extract and prepare clean dataset
    df_temp = pd.read_csv("/content/Nassau Candy Distributor.csv")
    df_temp["Order Date"] = pd.to_datetime(df_temp["Order Date"], format="%d-%m-%Y")
    df_temp["Ship Date"] = pd.to_datetime(df_temp["Ship Date"], format="%d-%m-%Y")
    df_temp["Lead_Time_Days"] = (df_temp["Ship Date"] - df_temp["Order Date"]).dt.days

    factory_mapping = {
        "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
        "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
        "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
        "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
        "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
        "Laffy Taffy": "Sugar Shack",
        "SweeTARTS": "Sugar Shack",
        "Nerds": "Sugar Shack",
        "Fun Dip": "Sugar Shack",
        "Fizzy Lifting Drinks": "Sugar Shack",
        "Everlasting Gobstopper": "Secret Factory",
        "Hair Toffee": "The Other Factory",
        "Lickable Wallpaper": "Secret Factory",
        "Wonka Gum": "Secret Factory",
        "Kazookles": "The Other Factory"
    }
    df_temp["Factory"] = df_temp["Product Name"].map(factory_mapping)
    df_temp["Order_Month"] = df_temp["Order Date"].dt.month
    df_temp["Order_Year"] = df_temp["Order Date"].dt.year

    ml_df_temp = df_temp[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year", "Lead_Time_Days"]].copy()
    X_temp = ml_df_temp[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year"]]
    y_temp = ml_df_temp["Lead_Time_Days"]

    X_train_temp, _, _, _ = train_test_split(X_temp, y_temp, test_size=0.20, random_state=42)

    categorical_features = ["Product Name", "Factory", "Region", "Ship Mode"]
    encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    encoder.fit(X_train_temp[categorical_features])
    encoded_columns = encoder.get_feature_names_out(categorical_features)

# Process scenario categorical columns
scenario_cat = scenario_orders[
    ["Product Name", "Scenario Factory", "Region", "Ship Mode"]
].copy()

scenario_cat = scenario_cat.rename(
    columns={"Scenario Factory": "Factory"}
)

scenario_encoded = encoder.transform(scenario_cat)

scenario_encoded_df = pd.DataFrame(
    scenario_encoded,
    columns=encoded_columns,
    index=scenario_orders.index
)

scenario_final = pd.concat(
    [
        scenario_encoded_df,
        scenario_orders[["Order_Month", "Order_Year"]]
    ],
    axis=1
)

print("Scenario Feature Shape:", scenario_final.shape)

Scenario Feature Shape: (50970, 30)

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor

# Fallback: Reconstruct and train gb_model if it is missing from the active session
if 'gb_model' not in globals():
    print("Model 'gb_model' not found in memory. Automatically retraining Gradient Boosting Regressor...")

    # 1. Load and prep data
    df_temp = pd.read_csv("/content/Nassau Candy Distributor.csv")
    df_temp["Order Date"] = pd.to_datetime(df_temp["Order Date"], format="%d-%m-%Y")
    df_temp["Ship Date"] = pd.to_datetime(df_temp["Ship Date"], format="%d-%m-%Y")
    df_temp["Lead_Time_Days"] = (df_temp["Ship Date"] - df_temp["Order Date"]).dt.days

    factory_mapping = {
        "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
        "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
        "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
        "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
        "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
        "Laffy Taffy": "Sugar Shack",
        "SweeTARTS": "Sugar Shack",
        "Nerds": "Sugar Shack",
        "Fun Dip": "Sugar Shack",
        "Fizzy Lifting Drinks": "Sugar Shack",
        "Everlasting Gobstopper": "Secret Factory",
        "Hair Toffee": "The Other Factory",
        "Lickable Wallpaper": "Secret Factory",
        "Wonka Gum": "Secret Factory",
        "Kazookles": "The Other Factory"
    }
    df_temp["Factory"] = df_temp["Product Name"].map(factory_mapping)
    df_temp["Order_Month"] = df_temp["Order Date"].dt.month
    df_temp["Order_Year"] = df_temp["Order Date"].dt.year

    ml_df_temp = df_temp[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year", "Lead_Time_Days"]].copy()
    X_temp = ml_df_temp[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year"]]
    y_temp = ml_df_temp["Lead_Time_Days"]

    X_train_temp, _, y_train_temp, _ = train_test_split(X_temp, y_temp, test_size=0.20, random_state=42)

    # 2. Encode
    categorical_features = ["Product Name", "Factory", "Region", "Ship Mode"]
    encoder_temp = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    X_train_encoded_temp = encoder_temp.fit_transform(X_train_temp[categorical_features])
    encoded_columns_temp = encoder_temp.get_feature_names_out(categorical_features)

    X_train_encoded_df_temp = pd.DataFrame(X_train_encoded_temp, columns=encoded_columns_temp, index=X_train_temp.index)
    X_train_final_temp = pd.concat([X_train_encoded_df_temp, X_train_temp[["Order_Month", "Order_Year"]]], axis=1)

    # 3. Fit Gradient Boosting model
    gb_model = GradientBoostingRegressor(n_estimators=200, learning_rate=0.05, max_depth=3, random_state=42)
    gb_model.fit(X_train_final_temp, y_train_temp)
    print("Model trained successfully.")

# Make predictions on our scenario configurations
scenario_orders["Predicted_Lead_Time"] = gb_model.predict(scenario_final)

print(scenario_orders[
    [
        "Product Name",
        "Current Factory",
        "Scenario Factory",
        "Scenario Type",
        "Predicted_Lead_Time"
    ]
].head(20))

Model 'gb_model' not found in memory. Automatically retraining Gradient Boosting Regressor...
Model trained successfully.
                         Product Name  Current Factory   Scenario Factory  \
0          Wonka Bar - Milk Chocolate  Wicked Choccy's    Wicked Choccy's
1          Wonka Bar - Milk Chocolate  Wicked Choccy's      Lot's O' Nuts
2          Wonka Bar - Milk Chocolate  Wicked Choccy's     Secret Factory
3          Wonka Bar - Milk Chocolate  Wicked Choccy's  The Other Factory
4          Wonka Bar - Milk Chocolate  Wicked Choccy's        Sugar Shack
5   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's    Wicked Choccy's
6   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's      Lot's O' Nuts
7   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's     Secret Factory
8   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's  The Other Factory
9   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's        Sugar Shack
10  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts    Wicked Choccy's
11  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts      Lot's O' Nuts
12  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts     Secret Factory
13  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts  The Other Factory
14  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts        Sugar Shack
15     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts    Wicked Choccy's
16     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts      Lot's O' Nuts
17     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts     Secret Factory
18     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts  The Other Factory
19     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts        Sugar Shack

   Scenario Type  Predicted_Lead_Time
0        Current          1092.436366
1    Alternative          1092.436366
2    Alternative          1041.869273
3    Alternative          1081.319297
4    Alternative          1087.125512
5        Current          1092.567570
6    Alternative          1092.567570
7    Alternative          1042.000476
8    Alternative          1081.450500
9    Alternative          1087.170792
10   Alternative          1107.534173
11       Current          1107.534173
12   Alternative          1056.967080
13   Alternative          1096.417104
14   Alternative          1102.223319
15   Alternative          1103.242810
16       Current          1103.242810
17   Alternative          1052.675716
18   Alternative          1092.125740
19   Alternative          1097.931955

In [ ]:
scenario_orders["Predicted_Improvement_Days"] = (
    scenario_orders.groupby("Product Name")["Predicted_Lead_Time"]
    .transform("first")
    - scenario_orders["Predicted_Lead_Time"]
)

print(scenario_orders[
    [
        "Product Name",
        "Current Factory",
        "Scenario Factory",
        "Scenario Type",
        "Predicted_Lead_Time",
        "Predicted_Improvement_Days"
    ]
].head(20))

                         Product Name  Current Factory   Scenario Factory  \
0          Wonka Bar - Milk Chocolate  Wicked Choccy's    Wicked Choccy's
1          Wonka Bar - Milk Chocolate  Wicked Choccy's      Lot's O' Nuts
2          Wonka Bar - Milk Chocolate  Wicked Choccy's     Secret Factory
3          Wonka Bar - Milk Chocolate  Wicked Choccy's  The Other Factory
4          Wonka Bar - Milk Chocolate  Wicked Choccy's        Sugar Shack
5   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's    Wicked Choccy's
6   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's      Lot's O' Nuts
7   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's     Secret Factory
8   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's  The Other Factory
9   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's        Sugar Shack
10  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts    Wicked Choccy's
11  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts      Lot's O' Nuts
12  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts     Secret Factory
13  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts  The Other Factory
14  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts        Sugar Shack
15     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts    Wicked Choccy's
16     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts      Lot's O' Nuts
17     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts     Secret Factory
18     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts  The Other Factory
19     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts        Sugar Shack

   Scenario Type  Predicted_Lead_Time  Predicted_Improvement_Days
0        Current          1092.436366                    0.000000
1    Alternative          1092.436366                    0.000000
2    Alternative          1041.869273                   50.567094
3    Alternative          1081.319297                   11.117069
4    Alternative          1087.125512                    5.310854
5        Current          1092.567570                    0.000000
6    Alternative          1092.567570                    0.000000
7    Alternative          1042.000476                   50.567094
8    Alternative          1081.450500                   11.117069
9    Alternative          1087.170792                    5.396778
10   Alternative          1107.534173                    0.000000
11       Current          1107.534173                    0.000000
12   Alternative          1056.967080                   50.567094
13   Alternative          1096.417104                   11.117069
14   Alternative          1102.223319                    5.310854
15   Alternative          1103.242810                    0.000000
16       Current          1103.242810                    0.000000
17   Alternative          1052.675716                   50.567094
18   Alternative          1092.125740                   11.117069
19   Alternative          1097.931955                    5.310854

In [ ]:
best_factory_recommendations = (
    scenario_orders
    .loc[
        scenario_orders.groupby("Product Name")["Predicted_Lead_Time"]
        .idxmin()
    ]
    [
        [
            "Product Name",
            "Current Factory",
            "Scenario Factory",
            "Predicted_Lead_Time",
            "Predicted_Improvement_Days"
        ]
    ]
    .reset_index(drop=True)
)

print(best_factory_recommendations)

                         Product Name    Current Factory   Scenario Factory  \
0              Everlasting Gobstopper     Secret Factory  The Other Factory
1                Fizzy Lifting Drinks        Sugar Shack     Secret Factory
2                             Fun Dip        Sugar Shack        Sugar Shack
3                         Hair Toffee  The Other Factory        Sugar Shack
4                           Kazookles  The Other Factory     Secret Factory
5                         Laffy Taffy        Sugar Shack     Secret Factory
6                  Lickable Wallpaper     Secret Factory     Secret Factory
7                               Nerds        Sugar Shack        Sugar Shack
8                           SweeTARTS        Sugar Shack     Secret Factory
9           Wonka Bar - Fudge Mallows      Lot's O' Nuts     Secret Factory
10         Wonka Bar - Milk Chocolate    Wicked Choccy's     Secret Factory
11  Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts     Secret Factory
12  Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's     Secret Factory
13     Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts     Secret Factory
14                          Wonka Gum     Secret Factory     Secret Factory

    Predicted_Lead_Time  Predicted_Improvement_Days
0           1326.429397                   13.889545
1            965.910530                  100.459888
2           1280.734690                   26.520432
3           1416.642847                   91.765608
4            988.596181                   15.031976
5            858.737798                   71.433454
6            990.998045                  105.649572
7            933.372673                   28.942209
8           1026.794289                   59.372176
9            950.211626                   61.038717
10           962.325841                  130.110526
11           989.725613                  117.808561
12           962.457044                  130.110526
13           973.132284                  130.110526
14           960.993740                   41.427847

In [ ]:
best_factory_recommendations["Improvement_%"] = (
    best_factory_recommendations["Predicted_Improvement_Days"]
    / (
        best_factory_recommendations["Predicted_Lead_Time"]
        + best_factory_recommendations["Predicted_Improvement_Days"]
    )
) * 100

print(best_factory_recommendations.round(2))

                         Product Name    Current Factory   Scenario Factory  \
0              Everlasting Gobstopper     Secret Factory  The Other Factory
1                Fizzy Lifting Drinks        Sugar Shack     Secret Factory
2                             Fun Dip        Sugar Shack        Sugar Shack
3                         Hair Toffee  The Other Factory        Sugar Shack
4                           Kazookles  The Other Factory     Secret Factory
5                         Laffy Taffy        Sugar Shack     Secret Factory
6                  Lickable Wallpaper     Secret Factory     Secret Factory
7                               Nerds        Sugar Shack        Sugar Shack
8                           SweeTARTS        Sugar Shack     Secret Factory
9           Wonka Bar - Fudge Mallows      Lot's O' Nuts     Secret Factory
10         Wonka Bar - Milk Chocolate    Wicked Choccy's     Secret Factory
11  Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts     Secret Factory
12  Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's     Secret Factory
13     Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts     Secret Factory
14                          Wonka Gum     Secret Factory     Secret Factory

    Predicted_Lead_Time  Predicted_Improvement_Days  Improvement_%
0               1326.43                       13.89           1.04
1                965.91                      100.46           9.42
2               1280.73                       26.52           2.03
3               1416.64                       91.77           6.08
4                988.60                       15.03           1.50
5                858.74                       71.43           7.68
6                991.00                      105.65           9.63
7                933.37                       28.94           3.01
8               1026.79                       59.37           5.47
9                950.21                       61.04           6.04
10               962.33                      130.11          11.91
11               989.73                      117.81          10.64
12               962.46                      130.11          11.91
13               973.13                      130.11          11.79
14               960.99                       41.43           4.13

In [ ]:
recommendation_table = best_factory_recommendations.sort_values(
    by="Improvement_%",
    ascending=False
).reset_index(drop=True)

print(recommendation_table.round(2))

                         Product Name    Current Factory   Scenario Factory  \
0          Wonka Bar - Milk Chocolate    Wicked Choccy's     Secret Factory
1   Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's     Secret Factory
2      Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts     Secret Factory
3   Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts     Secret Factory
4                  Lickable Wallpaper     Secret Factory     Secret Factory
5                Fizzy Lifting Drinks        Sugar Shack     Secret Factory
6                         Laffy Taffy        Sugar Shack     Secret Factory
7                         Hair Toffee  The Other Factory        Sugar Shack
8           Wonka Bar - Fudge Mallows      Lot's O' Nuts     Secret Factory
9                           SweeTARTS        Sugar Shack     Secret Factory
10                          Wonka Gum     Secret Factory     Secret Factory
11                              Nerds        Sugar Shack        Sugar Shack
12                            Fun Dip        Sugar Shack        Sugar Shack
13                          Kazookles  The Other Factory     Secret Factory
14             Everlasting Gobstopper     Secret Factory  The Other Factory

    Predicted_Lead_Time  Predicted_Improvement_Days  Improvement_%
0                962.33                      130.11          11.91
1                962.46                      130.11          11.91
2                973.13                      130.11          11.79
3                989.73                      117.81          10.64
4                991.00                      105.65           9.63
5                965.91                      100.46           9.42
6                858.74                       71.43           7.68
7               1416.64                       91.77           6.08
8                950.21                       61.04           6.04
9               1026.79                       59.37           5.47
10               960.99                       41.43           4.13
11               933.37                       28.94           3.01
12              1280.73                       26.52           2.03
13               988.60                       15.03           1.50
14              1326.43                       13.89           1.04

In [ ]:
recommendation_table.to_csv(
    "/content/factory_recommendations.csv",
    index=False
)

print("Recommendation table saved successfully.")

Recommendation table saved successfully.

In [ ]:
import pandas as pd
import numpy as np

# Fallback: Reconstruct recommendation_table if it is missing from the active session
if 'recommendation_table' not in globals():
    print("Variable 'recommendation_table' not found in memory. Reconstructing...")

    # Re-import and load clean dataset if necessary
    if 'df' not in globals() or 'Lead_Time_Days' not in df.columns:
        df = pd.read_csv("/content/Nassau Candy Distributor.csv")
        df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d-%m-%Y")
        df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d-%m-%Y")
        df["Lead_Time_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

        factory_mapping = {
            "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
            "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
            "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
            "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
            "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
            "Laffy Taffy": "Sugar Shack",
            "SweeTARTS": "Sugar Shack",
            "Nerds": "Sugar Shack",
            "Fun Dip": "Sugar Shack",
            "Fizzy Lifting Drinks": "Sugar Shack",
            "Everlasting Gobstopper": "Secret Factory",
            "Hair Toffee": "The Other Factory",
            "Lickable Wallpaper": "Secret Factory",
            "Wonka Gum": "Secret Factory",
            "Kazookles": "The Other Factory"
        }
        df["Factory"] = df["Product Name"].map(factory_mapping)
        df["Order_Month"] = df["Order Date"].dt.month
        df["Order_Year"] = df["Order Date"].dt.year

    # Recreate best_factory_recommendations if needed
    if 'best_factory_recommendations' not in globals():
        if 'scenario_orders' not in globals() or 'Predicted_Lead_Time' not in scenario_orders.columns:
            # If scenario predictions are also missing, we trigger the previous steps implicitly
            from sklearn.preprocessing import OneHotEncoder
            from sklearn.model_selection import train_test_split
            from sklearn.ensemble import GradientBoostingRegressor

            ml_df = df[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year", "Lead_Time_Days"]].copy()
            X = ml_df[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year"]]
            y = ml_df["Lead_Time_Days"]
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

            categorical_features = ["Product Name", "Factory", "Region", "Ship Mode"]
            encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
            encoder.fit(X_train[categorical_features])
            encoded_columns = encoder.get_feature_names_out(categorical_features)

            scenario_base = df[["Product Name", "Region", "Ship Mode", "Order_Month", "Order_Year", "Factory"]].copy()
            scenario_base = scenario_base.rename(columns={"Factory": "Current Factory"})
            all_factories = df["Factory"].unique().tolist()
            scenario_orders = scenario_base.merge(pd.DataFrame({"Scenario Factory": all_factories}), how="cross")

            scenario_orders["Scenario Type"] = scenario_orders.apply(
                lambda row: "Current" if row["Scenario Factory"] == row["Current Factory"] else "Alternative", axis=1
            )

            scenario_cat = scenario_orders[["Product Name", "Scenario Factory", "Region", "Ship Mode"]].copy()
            scenario_cat = scenario_cat.rename(columns={"Scenario Factory": "Factory"})
            scenario_encoded = encoder.transform(scenario_cat)
            scenario_encoded_df = pd.DataFrame(scenario_encoded, columns=encoded_columns, index=scenario_orders.index)
            scenario_final = pd.concat([scenario_encoded_df, scenario_orders[["Order_Month", "Order_Year"]]], axis=1)

            X_train_encoded = encoder.transform(X_train[categorical_features])
            X_train_encoded_df = pd.DataFrame(X_train_encoded, columns=encoded_columns, index=X_train.index)
            X_train_final = pd.concat([X_train_encoded_df, X_train[["Order_Month", "Order_Year"]]], axis=1)

            gb_model = GradientBoostingRegressor(n_estimators=200, learning_rate=0.05, max_depth=3, random_state=42)
            gb_model.fit(X_train_final, y_train)

            scenario_orders["Predicted_Lead_Time"] = gb_model.predict(scenario_final)
            scenario_orders["Predicted_Improvement_Days"] = (
                scenario_orders.groupby("Product Name")["Predicted_Lead_Time"].transform("first")
                - scenario_orders["Predicted_Lead_Time"]
            )

        best_factory_recommendations = (
            scenario_orders
            .loc[scenario_orders.groupby("Product Name")["Predicted_Lead_Time"].idxmin()]
            [["Product Name", "Current Factory", "Scenario Factory", "Predicted_Lead_Time", "Predicted_Improvement_Days"]]
            .reset_index(drop=True)
        )

        best_factory_recommendations["Improvement_%"] = (
            best_factory_recommendations["Predicted_Improvement_Days"]
            / (best_factory_recommendations["Predicted_Lead_Time"] + best_factory_recommendations["Predicted_Improvement_Days"])
        ) * 100

    recommendation_table = best_factory_recommendations.sort_values(
        by="Improvement_%",
        ascending=False
    ).reset_index(drop=True)

total_products = len(recommendation_table)

benefited_products = (
    recommendation_table["Predicted_Improvement_Days"] > 0
).sum()

average_improvement = recommendation_table[
    "Predicted_Improvement_Days"
].mean()

average_improvement_pct = recommendation_table[
    "Improvement_%"
].mean()

print("Total Products:", total_products)
print("Products with Predicted Improvement:", benefited_products)
print("Average Predicted Improvement (Days):", round(average_improvement, 2))
print("Average Predicted Improvement (%):", round(average_improvement_pct, 2))

Variable 'recommendation_table' not found in memory. Reconstructing...
Total Products: 15
Products with Predicted Improvement: 15
Average Predicted Improvement (Days): 74.91
Average Predicted Improvement (%): 6.82

In [ ]:
recommendation_coverage = (
    benefited_products / total_products
) * 100

print("Recommendation Coverage:", round(recommendation_coverage, 2), "%")

Recommendation Coverage: 100.0 %

In [ ]:
top_5_recommendations = recommendation_table.head(5)

print(top_5_recommendations[
    [
        "Product Name",
        "Current Factory",
        "Scenario Factory",
        "Predicted_Lead_Time",
        "Predicted_Improvement_Days",
        "Improvement_%"
    ]
].round(2))

                        Product Name  Current Factory Scenario Factory  \
0         Wonka Bar - Milk Chocolate  Wicked Choccy's   Secret Factory
1  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's   Secret Factory
2     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts   Secret Factory
3  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts   Secret Factory
4                 Lickable Wallpaper   Secret Factory   Secret Factory

   Predicted_Lead_Time  Predicted_Improvement_Days  Improvement_%
0               962.33                      130.11          11.91
1               962.46                      130.11          11.91
2               973.13                      130.11          11.79
3               989.73                      117.81          10.64
4               991.00                      105.65           9.63

In [ ]:
import pandas as pd

# Fallback: Reconstruct recommendation_table if it's missing from the active session
if 'recommendation_table' not in globals():
    print("Variable 'recommendation_table' not found in memory. Reconstructing...")
    if 'df' not in globals():
        df = pd.read_csv("/content/Nassau Candy Distributor.csv")
        df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d-%m-%Y")
        df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d-%m-%Y")
        df["Lead_Time_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days
        factory_mapping = {
            "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
            "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
            "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
            "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
            "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
            "Laffy Taffy": "Sugar Shack",
            "SweeTARTS": "Sugar Shack",
            "Nerds": "Sugar Shack",
            "Fun Dip": "Sugar Shack",
            "Fizzy Lifting Drinks": "Sugar Shack",
            "Everlasting Gobstopper": "Secret Factory",
            "Hair Toffee": "The Other Factory",
            "Lickable Wallpaper": "Secret Factory",
            "Wonka Gum": "Secret Factory",
            "Kazookles": "The Other Factory"
        }
        df["Factory"] = df["Product Name"].map(factory_mapping)
        df["Order_Month"] = df["Order Date"].dt.month
        df["Order_Year"] = df["Order Date"].dt.year

    if 'best_factory_recommendations' not in globals():
        from sklearn.preprocessing import OneHotEncoder
        from sklearn.model_selection import train_test_split
        from sklearn.ensemble import GradientBoostingRegressor

        ml_df = df[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year", "Lead_Time_Days"]].copy()
        X = ml_df[["Product Name", "Factory", "Region", "Ship Mode", "Order_Month", "Order_Year"]]
        y = ml_df["Lead_Time_Days"]
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

        categorical_features = ["Product Name", "Factory", "Region", "Ship Mode"]
        encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
        encoder.fit(X_train[categorical_features])
        encoded_columns = encoder.get_feature_names_out(categorical_features)

        scenario_base = df[["Product Name", "Region", "Ship Mode", "Order_Month", "Order_Year", "Factory"]].copy()
        scenario_base = scenario_base.rename(columns={"Factory": "Current Factory"})
        all_factories = df["Factory"].unique().tolist()
        scenario_orders = scenario_base.merge(pd.DataFrame({"Scenario Factory": all_factories}), how="cross")

        scenario_orders["Scenario Type"] = scenario_orders.apply(
            lambda row: "Current" if row["Scenario Factory"] == row["Current Factory"] else "Alternative", axis=1
        )

        scenario_cat = scenario_orders[["Product Name", "Scenario Factory", "Region", "Ship Mode"]].copy()
        scenario_cat = scenario_cat.rename(columns={"Scenario Factory": "Factory"})
        scenario_encoded = encoder.transform(scenario_cat)
        scenario_encoded_df = pd.DataFrame(scenario_encoded, columns=encoded_columns, index=scenario_orders.index)
        scenario_final = pd.concat([scenario_encoded_df, scenario_orders[["Order_Month", "Order_Year"]]], axis=1)

        X_train_encoded = encoder.transform(X_train[categorical_features])
        X_train_encoded_df = pd.DataFrame(X_train_encoded, columns=encoded_columns, index=X_train.index)
        X_train_final = pd.concat([X_train_encoded_df, X_train[["Order_Month", "Order_Year"]]], axis=1)

        gb_model = GradientBoostingRegressor(n_estimators=200, learning_rate=0.05, max_depth=3, random_state=42)
        gb_model.fit(X_train_final, y_train)

        scenario_orders["Predicted_Lead_Time"] = gb_model.predict(scenario_final)
        scenario_orders["Predicted_Improvement_Days"] = (
            scenario_orders.groupby("Product Name")["Predicted_Lead_Time"].transform("first")
            - scenario_orders["Predicted_Lead_Time"]
        )

        best_factory_recommendations = (
            scenario_orders
            .loc[scenario_orders.groupby("Product Name")["Predicted_Lead_Time"].idxmin()]
            [["Product Name", "Current Factory", "Scenario Factory", "Predicted_Lead_Time", "Predicted_Improvement_Days"]]
            .reset_index(drop=True)
        )
        best_factory_recommendations["Improvement_%"] = (
            best_factory_recommendations["Predicted_Improvement_Days"]
            / (best_factory_recommendations["Predicted_Lead_Time"] + best_factory_recommendations["Predicted_Improvement_Days"])
        ) * 100

    recommendation_table = best_factory_recommendations.sort_values(
        by="Improvement_%",
        ascending=False
    ).reset_index(drop=True)

# Calculate reallocation opportunities where the recommended factory differs from the current factory
actual_reallocations = (
    recommendation_table["Current Factory"] != recommendation_table["Scenario Factory"]
).sum()

print("Actual Reallocation Opportunities:", actual_reallocations)

Actual Reallocation Opportunities: 11

In [ ]:
low_impact = recommendation_table[
    recommendation_table["Current Factory"] != recommendation_table["Scenario Factory"]
].sort_values(
    by="Improvement_%",
    ascending=True
).head(5)

print(low_impact[
    [
        "Product Name",
        "Current Factory",
        "Scenario Factory",
        "Predicted_Improvement_Days",
        "Improvement_%"
    ]
].round(2))

                 Product Name    Current Factory   Scenario Factory  \
14     Everlasting Gobstopper     Secret Factory  The Other Factory
13                  Kazookles  The Other Factory     Secret Factory
9                   SweeTARTS        Sugar Shack     Secret Factory
8   Wonka Bar - Fudge Mallows      Lot's O' Nuts     Secret Factory
7                 Hair Toffee  The Other Factory        Sugar Shack

    Predicted_Improvement_Days  Improvement_%
14                       13.89           1.04
13                       15.03           1.50
9                        59.37           5.47
8                        61.04           6.04
7                        91.77           6.08

In [ ]:
reallocation_risk = recommendation_table[
    recommendation_table["Current Factory"] != recommendation_table["Scenario Factory"]
].copy()

reallocation_risk["Risk_Level"] = pd.cut(
    reallocation_risk["Improvement_%"],
    bins=[-float("inf"), 3, 7, float("inf")],
    labels=["High Risk", "Medium Risk", "Low Risk"]
)

print(
    reallocation_risk[
        [
            "Product Name",
            "Current Factory",
            "Scenario Factory",
            "Improvement_%",
            "Risk_Level"
        ]
    ].round(2)
)

                         Product Name    Current Factory   Scenario Factory  \
0          Wonka Bar - Milk Chocolate    Wicked Choccy's     Secret Factory
1   Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's     Secret Factory
2      Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts     Secret Factory
3   Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts     Secret Factory
5                Fizzy Lifting Drinks        Sugar Shack     Secret Factory
6                         Laffy Taffy        Sugar Shack     Secret Factory
7                         Hair Toffee  The Other Factory        Sugar Shack
8           Wonka Bar - Fudge Mallows      Lot's O' Nuts     Secret Factory
9                           SweeTARTS        Sugar Shack     Secret Factory
13                          Kazookles  The Other Factory     Secret Factory
14             Everlasting Gobstopper     Secret Factory  The Other Factory

    Improvement_%   Risk_Level
0           11.91     Low Risk
1           11.91     Low Risk
2           11.79     Low Risk
3           10.64     Low Risk
5            9.42     Low Risk
6            7.68     Low Risk
7            6.08  Medium Risk
8            6.04  Medium Risk
9            5.47  Medium Risk
13           1.50    High Risk
14           1.04    High Risk

In [ ]:
print(
    reallocation_risk["Risk_Level"]
    .value_counts()
    .reindex(["Low Risk", "Medium Risk", "High Risk"])
)

Risk_Level
Low Risk       6
Medium Risk    3
High Risk      2
Name: count, dtype: int64

In [ ]:
print(df[["Sales", "Gross Profit", "Cost"]].describe())

              Sales  Gross Profit          Cost
count  10194.000000  10194.000000  10194.000000
mean      13.908537      9.166451      4.742087
std       11.341020      6.643740      5.061647
min        1.250000      0.250000      0.600000
25%        7.200000      4.900000      2.400000
50%       10.800000      7.470000      3.600000
75%       18.000000     12.250000      5.700000
max      260.000000    130.000000    130.000000

In [ ]:
product_profit = (
    df.groupby("Product Name")["Gross Profit"]
    .agg(["count", "mean", "median"])
    .reset_index()
    .sort_values("mean", ascending=False)
)

print(product_profit.round(2))

                         Product Name  count   mean  median
6                  Lickable Wallpaper     94  41.81   40.00
0              Everlasting Gobstopper      3  34.67   32.00
3                         Hair Toffee      4  14.88   17.50
13     Wonka Bar -Scrumdiddlyumptious   2064   9.38    7.50
11  Wonka Bar - Nutty Crunch Surprise   1810   9.29    7.47
12  Wonka Bar - Triple Dazzle Caramel   2015   9.24    7.35
9           Wonka Bar - Fudge Mallows   1818   9.13    7.20
10         Wonka Bar - Milk Chocolate   2137   8.16    6.33
1                Fizzy Lifting Drinks      6   7.88    7.88
5                         Laffy Taffy     10   3.35    2.48
8                           SweeTARTS     10   2.87    2.80
14                          Wonka Gum    120   2.59    1.95
7                               Nerds      4   1.75    1.75
2                             Fun Dip      3   1.60    1.80
4                           Kazookles     96   0.97    0.75

In [ ]:
recommendation_profit = recommendation_table.merge(
    product_profit[["Product Name", "mean"]],
    on="Product Name",
    how="left"
)

recommendation_profit = recommendation_profit.rename(
    columns={"mean": "Avg_Gross_Profit"}
)

print(
    recommendation_profit[
        [
            "Product Name",
            "Current Factory",
            "Scenario Factory",
            "Improvement_%",
            "Avg_Gross_Profit"
        ]
    ].round(2)
)

                         Product Name    Current Factory   Scenario Factory  \
0          Wonka Bar - Milk Chocolate    Wicked Choccy's     Secret Factory
1   Wonka Bar - Triple Dazzle Caramel    Wicked Choccy's     Secret Factory
2      Wonka Bar -Scrumdiddlyumptious      Lot's O' Nuts     Secret Factory
3   Wonka Bar - Nutty Crunch Surprise      Lot's O' Nuts     Secret Factory
4                  Lickable Wallpaper     Secret Factory     Secret Factory
5                Fizzy Lifting Drinks        Sugar Shack     Secret Factory
6                         Laffy Taffy        Sugar Shack     Secret Factory
7                         Hair Toffee  The Other Factory        Sugar Shack
8           Wonka Bar - Fudge Mallows      Lot's O' Nuts     Secret Factory
9                           SweeTARTS        Sugar Shack     Secret Factory
10                          Wonka Gum     Secret Factory     Secret Factory
11                              Nerds        Sugar Shack        Sugar Shack
12                            Fun Dip        Sugar Shack        Sugar Shack
13                          Kazookles  The Other Factory     Secret Factory
14             Everlasting Gobstopper     Secret Factory  The Other Factory

    Improvement_%  Avg_Gross_Profit
0           11.91              8.16
1           11.91              9.24
2           11.79              9.38
3           10.64              9.29
4            9.63             41.81
5            9.42              7.88
6            7.68              3.35
7            6.08             14.88
8            6.04              9.13
9            5.47              2.87
10           4.13              2.59
11           3.01              1.75
12           2.03              1.60
13           1.50              0.97
14           1.04             34.67

In [ ]:
print("===== FINAL PROJECT KPIs =====")

print("Best Model: Gradient Boosting")
print("RMSE: 181.65")
print("MAE: 179.94")
print("R²: 0.5334")

print("\nAverage Predicted Improvement: 6.82%")
print("Average Predicted Improvement Days: 74.91 days")

print("Recommendation Coverage: 100%")
print("Actual Reallocation Opportunities: 11")

print("\nRisk Distribution:")
print(reallocation_risk["Risk_Level"].value_counts())

print("\nProfit Impact:")
print("Direct profit impact cannot be measured from available factory-change data.")
print("Gross Profit was used as a business-priority indicator.")

===== FINAL PROJECT KPIs =====
Best Model: Gradient Boosting
RMSE: 181.65
MAE: 179.94
R²: 0.5334

Average Predicted Improvement: 6.82%
Average Predicted Improvement Days: 74.91 days
Recommendation Coverage: 100%
Actual Reallocation Opportunities: 11

Risk Distribution:
Risk_Level
Low Risk       6
Medium Risk    3
High Risk      2
Name: count, dtype: int64

Profit Impact:
Direct profit impact cannot be measured from available factory-change data.
Gross Profit was used as a business-priority indicator.

In [ ]:
he Factory Reallocation & Shipping Optimization system successfully analyzed historical shipping patterns, predicted lead times, simulated alternative factory assignments, and generated model-based factory recommendations. Among the evaluated models, Gradient Boosting performed best with an R² of 0.5334 and RMSE of 181.65 days. Scenario analysis identified 11 actual product reallocation opportunities, with an average model-predicted lead-time improvement of 74.91 days (6.82%). The recommendations were further prioritized using a project-defined risk classification, resulting in 6 low-risk, 3 medium-risk, and 2 high-risk opportunities. Gross Profit was analyzed as a business-priority indicator; however, direct profit impact from factory reassignment could not be measured from the available historical data. Therefore, the recommendations should be treated as model-based decision-support suggestions rather than guaranteed operational outcomes.